### ISSUE TITLE
Client Crash after trying to search for item

### ISSUE THREAD

**Issue by smmmadden** [shedaniel/RoughlyEnoughItems#1211] opened 2022-11-10 12:30 UTC
### What happened?

I opened the inventory display (in creative) and tried to search for glow ink sack and the client crashed as soon as I typed in the first two letters.....gl
![image](https://user-images.githubusercontent.com/10309346/201090579-82137d88-2281-4964-acc0-e7af15d82058.png)
![image](https://user-images.githubusercontent.com/10309346/201090604-b5532bd9-b775-4576-b9f6-f7a2cb928887.png)

I also created an issue on Domum Ornamentum since both are referenced https://github.com/ldtteam/Domum-Ornamentum/issues/106#issue-1443762557

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Full crash: https://pastebin.com/np8DCAeL
```

### Anything else?

It happens in Survival or Creative Mode typing in the Search... dialog
(before it crashes - survival mode)
![image](https://user-images.githubusercontent.com/10309346/201091853-551c48b3-7470-4140-9c46-77fded04d9e8.png)
(before it crashes - creative mode)
![image](https://user-images.githubusercontent.com/10309346/201092076-938e6fa8-a3c4-4e44-9aa5-0cda488ee9d4.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by smmmadden** [comment] 2022-11-10 12:36
I also just now tried searching in the top of the inventory UI and it crashed there as well (with just one letter typed...a for axe), so definitely "search" related.
![image](https://user-images.githubusercontent.com/10309346/201093230-3295adc7-32d4-4d5b-83dc-06dc9234b12f.png)

**Comment by shedaniel** [comment] 2022-11-10 12:37
It isn’t caused by REI, when you search in REI, and when REI shows you that item, it crashes, it is on that mod to make sure it doesn’t crash when it renders.

**Comment by smmmadden** [comment] 2022-11-10 12:45
not sure I follow.  The item in question is a vanilla item (axe, glow ink sack, etc.) and the item is never shown b/c it crashes immediately.  Are you saying it is an issue with the Donum Ornamentum mod?

**Comment by shedaniel** [comment] 2022-11-10 12:55
That’s the reason, it never shows because it cannot show. I will close this issue on the REI side.

**Closed as completed by shedaniel** 2022-11-10 12:55 UTC
Labels: bug
