### ISSUE TITLE
What am i supposed to do with this? does this 2 mods doesn't works together?

### ISSUE THREAD

**Issue by shedaniel** [shedaniel/RoughlyEnoughItems#912] opened 2022-06-12 17:00 UTC
### Discussed in https://github.com/shedaniel/RoughlyEnoughItems/discussions/906

User was not able to continue from warning.

<div type='discussions-op-text'>

<sup>Originally posted by **bubble13699** June 12, 2022</sup>
![Untitled](https://user-images.githubusercontent.com/101046132/173221852-3c835507-3d23-493b-9051-d8da1786cf0f.png)
</div>

**Comment by rdrpenguin04** [comment] 2022-06-14 21:44
This may actually be a duplicate of #897

**Closed as completed** 2022-06-14 23:16 UTC
Labels: bug, status: duplicate
