### ISSUE TITLE
[Feature] Disable tag category and processing

### ISSUE THREAD

**Issue by Xetaxheb** [shedaniel/RoughlyEnoughItems#1095] opened 2022-08-23 15:41 UTC
### What is your feature request?

A config option to disable tag category completely and disable whatever processing is done to support it on boot (if it's any real overhead)

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment] 2022-09-08 07:23
Duplicate of #669

**Closed as completed by shedaniel** 2022-09-08 07:23 UTC
Labels: status: duplicate, enhancement
