### ISSUE TITLE
[Bug] Search Bar Not Working 

### ISSUE THREAD

**Issue by KoleOnIce** [shedaniel/RoughlyEnoughItems#1064] opened 2022-08-08 22:01 UTC
### What happened?

![Minecraft Screenshot 2022 08 08 - 17 49 33 99](https://user-images.githubusercontent.com/77826610/183520881-b409dae5-e1a5-45b4-a112-7eabce527208.png)
The modpack we are using is AQM2. All of my friends' search bars are working, but mine isn't. I'm not sure if Wurst has anything to do with it. My search bar was working when we first started it up but now it just won't do anything.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
I included them below.
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9285241/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9285242/rei.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9285243/rei-issues.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-08-10 18:54
Duplicate of #1034

**Closed as completed by shedaniel** 2022-08-10 18:54 UTC
Labels: bug, status: duplicate
