### ISSUE TITLE
Effects not showing in inventory and "crash" when opening recipe with hotkey

### ISSUE THREAD

**Issue by muluffel** [shedaniel/RoughlyEnoughItems#715] opened 2022-01-16 14:06 UTC
**Describe the bug**
In the inventory, there is the space for the potion/beacon effects but the effects are not showing

Also sometimes, when setting a hotkey (r) for showing the recipe and searching for an item in creative mode inventory with r in the name (e.g. netheR bricks) as soon as pressing the r key in the search and the cursor is over an item, the recipe opens and when I press escape, I can't go back in game. It doesn't freeze - I still can see everything happen in game but I cannot move or press any key so I need to crash with Alt+F4

**Steps to Reproduce**
- First Issue: Just have some Beacon or potion effects.
- Second Issue: Search for an item in creative mode inventory containing R. The recipe will open, when pressing escape, you won't be able to move or press any key.

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/65601356/149663251-cf169a83-554c-487d-a833-5d535696a23c.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.8
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/NFFPG3uh

**Comment by shedaniel** [comment] 2022-01-16 14:23
Update replay mod

**Comment by shedaniel** [comment] 2022-01-16 14:23
Duplicate of #595

**Closed as completed by shedaniel** 2022-01-16 14:23 UTC
Labels: bug, status: duplicate

**Comment by muluffel** [comment] 2022-01-16 14:35
my main issue was that i cannot see the effects with does not seem to be resolved with updating reeplaymod
