### ISSUE TITLE
[Bug] REI Search Bar Not Working

### ISSUE THREAD

**Issue by OfficialBlueShell** [shedaniel/RoughlyEnoughItems#1073] opened 2022-08-13 01:47 UTC
### An error preventing search feature from searching specific items?

Im using the Medieval MC Fabric pack v4 and the search bar doesnt update the list of items when typing in a query. The only time it updates is when searching by mod (@[MODNAME]). I saw a previous issue with this where the solution was removing SkyLib but I dont have SkyLib in this pack so another thing is conflicting. Other people using this pack dont seem to be having the same issue as me.

The logs show constant output of errors.

Attempted fixes: I've uninstalled and reinstalled the pack. This fixed the issue for about 10 minutes and then the problem returned. I tried disabling all resource packs and shaders in case naming conventions were an issue and it didn't seem to change anything. 

Any info on this issue would be greatly appreciated.

![2022-08-12_21 22 40](https://user-images.githubusercontent.com/111162572/184463611-a6c596d2-161c-49ea-b9b6-080cd308fad8.png)
![2022-08-12_21 22 45](https://user-images.githubusercontent.com/111162572/184463613-f2da21f8-4f5b-4896-bb06-da9cdec3896e.png)
![2022-08-12_21 22 54](https://user-images.githubusercontent.com/111162572/184463614-5b8de3ab-db51-4421-9841-fe74337df03f.png)
![2022-08-12_21 23 05](https://user-images.githubusercontent.com/111162572/184463616-55772f6d-a7ca-4fb1-b0f6-4a29cc36da9c.png)
.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
...
[21:19:35] [Render thread/ERROR]: @ Render
[21:19:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:20:26] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=0, source=API, type=ERROR, severity=HIGH, message='Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=9684 javaw.exe 64bit)'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=0, source=API, type=ERROR, severity=HIGH, message='Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=9684 javaw.exe 64bit)'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:27] [Render thread/INFO]: OpenGL debug message: id=0, source=API, type=ERROR, severity=HIGH, message='Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=9684 javaw.exe 64bit)'
...
[21:20:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:20:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:20:35] [Render thread/ERROR]: @ Render
[21:20:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:20:39] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
[21:20:39] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
[21:20:39] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
[21:20:39] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:39] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
...
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:44] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:45] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
[21:20:45] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to map buffer.'
...
[21:30:03] [Render thread/ERROR]: 65539: Invalid key -1
[21:30:03] [Render thread/ERROR]: ########## GL ERROR ##########
[21:30:03] [Render thread/ERROR]: @ Render
[21:30:03] [Render thread/ERROR]: 65539: Invalid key -1
[21:31:13] [Render thread/ERROR]: ########## GL ERROR ##########
[21:31:13] [Render thread/ERROR]: @ Render
[21:31:13] [Render thread/ERROR]: 65539: Invalid key -1
[21:31:13] [Render thread/ERROR]: ########## GL ERROR ##########
[21:31:13] [Render thread/ERROR]: @ Render
[21:31:13] [Render thread/ERROR]: 65539: Invalid key -1
[21:31:15] [pool-4-thread-1/WARN]: Attempted to send com.jagrosh.discordipc.entities.RichPresence@4b889a6 to the client before it was ready
[21:31:40] [Render thread/ERROR]: ########## GL ERROR ##########
[21:31:40] [Render thread/ERROR]: @ Render
[21:31:40] [Render thread/ERROR]: 65539: Invalid key -1
[21:31:40] [Render thread/ERROR]: ########## GL ERROR ##########
[21:31:40] [Render thread/ERROR]: @ Render
[21:31:40] [Render thread/ERROR]: 65539: Invalid key -1
[21:31:40] [Render thread/ERROR]: ########## GL ERROR ##########
[21:31:40] [Render thread/ERROR]: @ Render
[21:31:40] [Render thread/ERROR]: 65539: Invalid key -1
...
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9330557/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9330558/rei.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by DemonMartin** [comment] 2022-08-14 20:32
Similar Issue here, searching any items does not work, searching Mods using @name, does work tho. Tho, it‘s in a custom Modpack I‘m working on. I will send my logs here tmrw when I‘m back home.

**Comment by shedaniel** [comment] 2022-08-15 14:39
Duplicate of #1034

**Closed as completed by shedaniel** 2022-08-15 14:39 UTC
Labels: bug, status: duplicate
