### ISSUE TITLE
CTD when opening any screen which would show REI[Bug]

### ISSUE THREAD

**Issue by xAlicatt** [shedaniel/RoughlyEnoughItems#153] opened 2019-08-30 16:05 UTC
**Describe the bug**
This has been happening with all versions past Build 3 for 1.14. I can use Build 3 with no issues, but anything newer than that and opening the inventory (basically anything that would show REI on the side), and the game crashes. It is a crash to desktop, but fortunately I do get a report.

**Steps to Reproduce**
- Open any screen that would show REI on the side
- Game crash

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.4
 - Mod Loader: Fabric 0.6.1 build164

**Logs**
https://paste.ee/p/1LaRr This is a crash report. 

**Additional context**
I do have other mods installed, and as no one else has reported this, I'm guessing it must be a conflict with one of them, but since it doesn't happen with builds 3 or prior, it's seems like it's a change that has been made in REI.

**Comment by AsheX1** [comment] 2019-08-30 16:40
i can't even boot no crash log to. 
version: [Fabric 1.14.x, 19w34a - 19w35a] v3.1.1 Build 8
fabric build 164
launcher output is all i can get 

18:34:44.437
Preparing to launch minecraft client for fabric-loader-0.6.1+build.164-1.14.4
18:34:44.863
Checking installations.
18:34:44.864
Minecraft client fabric-loader-0.6.1+build.164-1.14.4 is ready to start.
18:34:44.864
Starting!
18:34:44.910
Using default game log configuration client-1.12.xml (outputs XML)
18:34:45.334
Loading for game Minecraft 1.14.4
18:34:48.052
  <log4j:Event logger="FabricLoader" timestamp="1567182885334" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading for game Minecraft 1.14.4]]></log4j:Message>
  </log4j:Event>
18:34:49.229
Process crashed with exit code 1

going back to [Fabric 1.14.3 - 1.14.4] v2.9.8 Build 150
works fine now.?.?

**Comment by xAlicatt** [comment] 2019-08-31 01:29
@startjim you should make your own report...your issue is unrelated with this one.

**Comment by shedaniel** [comment] 2019-08-31 02:27
Duplicate of #151, conflict with Orderly

**Comment by shedaniel** [comment] 2019-08-31 02:28
Update Orderly to fix this

**Closed as completed by shedaniel** 2019-08-31 02:27 UTC
Labels: bug, status: duplicate, status: invalid, other mods
