### ISSUE TITLE
[Bug] Messed up highlighting and overlay order in 'search inventory'

### ISSUE THREAD

**Issue by XenoTheStrange** [shedaniel/RoughlyEnoughItems#621] opened 2021-09-04 19:22 UTC
**Describe the bug**
When you search for a thing and then hover over items in your inventory, all items that don't fit the description become even more grey for some reason. If you're hovering over many things to get to the item you're trying to grab, it might be quite flashy, which is annoying.
ex. when you hover over an empty space, matching items are highlighted and others are grey. When you hover over any item, the grey items get even darker. If you happen to be scrolling between items and blank spaces often enough, this will make the non-matching items flash a bunch, going from dim to dimmer.
These grey squares also appear above the item description "oak planks etc" normal popup.

**Steps to Reproduce**
- double click search bar and search inventory for a thing
- hover over different items
- optional, put an item in every other slot, search, then scroll over them to see lots of flashy as the items become more and less dim over and over again.

**Screenshots**
Not hovering:
![image](https://user-images.githubusercontent.com/48196283/132105743-3bb96023-8259-4704-a7d5-7ef3041a46e6.png)

Hovering:
![2021-09-04_12 22 37](https://user-images.githubusercontent.com/48196283/132105805-839bce2a-7819-41f6-83cc-e61adb9f9acd.png)

Flashy:
https://user-images.githubusercontent.com/48196283/132105850-2058fcbd-bf8b-49c8-bb6a-0362180869fd.mp4

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Additional context**
the unselected bits are already not highlighted, why do they need to get darker when I hover over an item?
Is this the same overlay appearing again on accident?

**Comment by shedaniel** [comment] 2022-05-19 18:31
Duplicate of #541

**Closed as completed by shedaniel** 2022-05-19 18:31 UTC
Labels: bug
