### ISSUE TITLE
[Feature] Time util

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#369] opened 2020-07-01 12:07 UTC
**Describe the solution you'd like**
An util button for setting the time. The four vanilla presets are fine (noon, day, night, midnight), no need to invent new ones.

**Additional context**
Also you promised to move weather util to the same line as config and gamemode util, so if you add time, move it there too 😁

**Comment by shedaniel** [comment] 2020-07-18 07:40
Duplicate of #110

**Closed as completed by shedaniel** 2020-07-18 07:40 UTC
Labels: enhancement
