### ISSUE TITLE
[Bug] Search Bar and Recipes don't function correctly.

### ISSUE THREAD

**Issue by FooterManDev** [shedaniel/RoughlyEnoughItems#1377] opened 2023-03-09 23:08 UTC
### What happened?

When attempting to search in REI, the list on the right doesn't update, but only if not using a special search prefix, but nothing added after the prefix works either (For example, searching for "Andesite Alloy" normally doesn't work, "@ create" works, but anything after that doesn't.)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Can't drop / paste anything in this field :/
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10937020/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10937032/rei.log)
Also using REP, RET addons.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by FooterManDev** [comment] 2023-03-10 02:29
Update, apparently I can't see recipes either 👀

**Comment by shedaniel** [comment] 2023-03-10 18:00
Duplicate of #1297

**Closed as not planned** 2023-03-10 18:01 UTC
Labels: bug, status: duplicate
