### ISSUE TITLE
[Forge 1.18.1 Bug] Missing Recipes from latest updates

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#790] opened 2022-02-19 20:59 UTC
### What happened?

Since the latest update of REI with what I assume is the new JEI 9.3 API, a lot of items from other mods categories are not showing recipes when hovering and pressing "R" or left clicking, right clicking, or pressing "U". Some mods like Mystical Agriculture, Tinkers, and a lot others that have their own category. 

I found a work around and that is browsing via categories, finding the category for that specific item, and then clicking the item in that categories recipe. This will then allow all those items that fall in that category to have their recipe opened using mouse clicks and hotkeys. 

![image](https://user-images.githubusercontent.com/35115304/154818836-9f044cde-8209-43da-b99e-320e9471f1a3.png)

(Clicking this does nothing)

![image](https://user-images.githubusercontent.com/35115304/154818839-694c971d-0279-4119-beab-ff4bdc7031a5.png)
When manually finding the item in the category, and then left clicking it, the recipe is now "available"

![image](https://user-images.githubusercontent.com/35115304/154818861-328c839a-1a89-4810-9a52-5b262a48989f.png)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Latest.log : https://gist.github.com/itsdinkd/44e22a1b8f03794dae2cd825953cf11e
REI Log: https://gist.github.com/itsdinkd/2a6eb06283dc797d351250569fc6c869
```

**Comment by Sunekaer** [comment] 2022-02-20 16:35
Duplicate of #787

**Closed as completed** 2022-02-20 20:00 UTC
Labels: bug, status: duplicate
