### ISSUE TITLE
[Bug] crashed when I look up the usage of "Certus Quartz Crystal" of ae2

### ISSUE THREAD

**Issue by tgh666** [shedaniel/RoughlyEnoughItems#1253] opened 2022-11-30 15:58 UTC
### What happened?

[crash-2022-11-30_23.31.07-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/10124859/crash-2022-11-30_23.31.07-client.txt)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10124873/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10124875/rei.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-11-30 16:34
Please keep the issues in English!

**Comment by tgh666** [comment] 2022-11-30 16:39
It crashed when I look up the usage of "Certus Quartz Crystal" of ae2

**Comment by shedaniel** [comment] 2022-12-10 08:37
What is your REI, REI Plugin Compat and AE2 versions?

**Comment by tgh666** [comment] 2022-12-10 08:51
REI  9.1.574
REC  9.0.37
AE2  12.8.4

> What is your REI, REI Plugin Compat and AE2 versions?

**Comment by shedaniel** [comment] 2022-12-10 08:56
Update.

**Comment by shedaniel** [comment] 2022-12-10 13:16
Duplicate of #1177

**Closed as completed by shedaniel** 2022-12-10 13:16 UTC
Labels: bug, status: duplicate, other mods
