### ISSUE TITLE
[Feature]Way to filter out item groups such as facades et al

### ISSUE THREAD

**Issue by zeflap** [shedaniel/RoughlyEnoughItems#228] opened 2019-12-29 19:17 UTC
**Describe the solution you'd like**
Some way of being able to hide items, as discussed on the fabric discord

**Comment by zeflap** [comment] 2019-12-29 19:17
Oh, apparently already wished for in #115 and #120 partially as well

**Comment by shedaniel** [comment] 2020-01-28 08:19
Duplicate of #115

**Closed as completed by shedaniel** 2020-01-28 08:19 UTC
Labels: status: duplicate, enhancement
