### ISSUE TITLE
[Feature] Custom item with recipe support

### ISSUE THREAD

**Issue by Noxmore** [shedaniel/RoughlyEnoughItems#891] opened 2022-06-05 07:40 UTC
### What is your feature request?

First, i'll say that i'm not even sure if this is technically possible, since i'm pretty inexperienced in modding, but if you can, this would be pretty cool i think.

Let's say that a server adds a custom recipe from a datapack/plugin/etc that has a custom recipe for let's say a stick with some special properties/nbts, a custom item.
I think it would be nice to have that custom item show up in the item list, with the custom recipe, and be able to be spawned in.

This would almost definitely have an option to turn it on and off, possibly per-server, because this might not be the best on every server.
The other thing is that i really doubt this would work with custom crafting systems, (Like Hypixel Skyblock's crafting gui) but mods like Not enough updates fill that role.

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment] 2022-06-12 07:24
This is possible, I am considering if this should be in the main mod or via an addon

**Comment by shedaniel** [comment] 2022-11-28 16:31
Duplicate of #481

**Closed as completed by shedaniel** 2022-11-28 16:31 UTC
Labels: status: duplicate, enhancement
