### ISSUE TITLE
[Bug] Game crashing upon opening controls

### ISSUE THREAD

**Issue by RillingDev** [shedaniel/RoughlyEnoughItems#246] opened 2020-01-14 18:11 UTC
**Describe the bug**
Game crashing upon opening controls settings (after a few seconds)

**Steps to Reproduce**
- Start Minecraft
- Open Settings -> Controls
- Wait a few seconds (4 to 5 seconds usually)

**Screenshots**
-

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: Fabric 0.7.4 build 177 (Fabric API version 0.4.27+build.286-1.15)
- REI: 3.3.8

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/7mGvA9Nz

**Additional context**
- Clean setup with no other mods; Without REI this issue does not occur.

**Comment by shedaniel** [comment] 2020-01-15 04:03
Unable to reproduce in development environment, will be looking deep into this issue later.

**Comment by leasoncre** [comment] 2020-01-19 18:35
might be related, not sure:
Launch game, open inventory, click on a lingering potion to view recipe, and game crashes. (single player)
[crash-2020-01-19_13.33.50-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/4083176/crash-2020-01-19_13.33.50-client.txt)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/4083180/latest.log)

**Comment by shedaniel** [comment] 2020-01-19 23:11
Fixed in dev. waiting for update.

**Closed as completed** 2020-01-22 15:43 UTC
Labels: bug

**Comment by RillingDev** [comment] 2020-01-22 17:53
Can confirm it is fixed. Thanks for fixing and for the great mod!
