### ISSUE TITLE
[Bug] Hiding items

### ISSUE THREAD

**Issue by Romz24** [shedaniel/RoughlyEnoughItems#860] opened 2022-05-21 19:07 UTC
### What happened?

I'm trying to hide all facades from the mod [Simple BC Pipes](https://www.curseforge.com/minecraft/mc-mods/simplepipes), but they are still displayed. I even tried to select all objects and hide them. But facades are still visible in the list.

With other items, there is no such error, I cannot hide only facades from the list.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [x] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
There are no errors in the logs
```

### Anything else?

```
"filteredStacks": [
	"{Count:1b,id:\"simple_pipes:facade\",type:\"minecraft:item\"}"
]
```

![image](https://user-images.githubusercontent.com/2458113/169665747-bed18be9-5571-414a-8543-1834ef89e31c.png)
![image](https://user-images.githubusercontent.com/2458113/169665767-e2567a91-cd28-4d44-8bd7-ece0c08c6a3a.png)

**Comment by shedaniel** [comment] 2022-05-29 07:41
Duplicate of #667

**Closed as completed** 2022-05-29 07:41 UTC
Labels: bug, status: duplicate
