### ISSUE TITLE
[Bug] 1.19.2 FontSet.getGlyphInfo fails due to concurrency

### ISSUE THREAD

**Issue by spunchbop121** [shedaniel/RoughlyEnoughItems#1409] opened 2023-05-13 12:56 UTC
### What happened?

The game crashed after I pressed the "U" key when the cursor covered the shell item from the Twigs mod.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
crash_client, latest.log and rei.log are attached below
```

### Anything else?

[crash-2023-05-13_13.44.30-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/11469709/crash-2023-05-13_13.44.30-client.txt)

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/11469710/latest.log)

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/11469712/rei.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-05-29 05:32
Duplicate of #1285

**Closed as not planned by shedaniel** 2023-05-29 05:32 UTC
Labels: bug, status: duplicate, priority: medium, note: confirmed
