### ISSUE TITLE
[Bug] If blocks/items have the same name as their mods name it doesn't say the name of the block/item on the mod name

### ISSUE THREAD

**Issue by RemagOfficial** [shedaniel/RoughlyEnoughItems#1495] opened 2023-09-06 14:24 UTC
### What happened?

i made a mod that adds a bunch of compressed cobblestones and the mod name is Trevigintuple Compressed Cobblestone and as the name suggests it adds trevigintuple compressed cobblestone but in REI it doesn't say the name of the block only the mod name

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
shouldnt be needed as it doesnt log anything
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-09-18 07:42
This is a duplicate of #1362 which is already fixed, are you sure this issue is occuring anymore, or do you have an outdated version of REI? I can't check your REI version because you didn't attach any logs.

**Closed as not planned by shedaniel** 2023-09-18 07:42 UTC
Labels: bug, status: duplicate

**Comment by RemagOfficial** [comment] 2023-09-20 10:50
I wouldn't be surprised if it's outdated, I installed it ages ago
