### ISSUE TITLE
[Bug] Opened a tree hollow from tree hollows and got this crash

### ISSUE THREAD

**Issue by Sunconure11** [shedaniel/RoughlyEnoughItems#1622] opened 2024-04-27 22:09 UTC
### What happened?

Opening a hollow gave me this crash

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://gist.github.com/Sunconure11/0a6d7bc72c7db8245624d70bce32f1b8
```

### Anything else?

Of note is that I turned on a few more experimental settings in FerriteCore and ModernFix, to reduce memory usage a bit.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2024-04-29 15:51
Duplicate of #1614

**Closed as completed by shedaniel** 2024-04-29 15:51 UTC
Labels: bug, status: duplicate
