### ISSUE TITLE
[Feature] Add "Tabs" or "Groups" to the bookmarks sidebar

### ISSUE THREAD

**Issue by nmay231** [shedaniel/RoughlyEnoughItems#616] opened 2021-08-28 10:45 UTC
**Describe the solution you'd like**
It would be nice to split your bookmarked/favorited items into different groups. Here is how I imagine the controls:

- Pressing A adds or removes bookmarked items as before. Items are added to group 1 by default.
- Pressing 1-9 on a bookmarked item moves it to that group where groups are sorted top to bottom (1 to 9).
- Extra: Allow naming of groups
- Extra: Pressing 1-9 on the group header allows you to reorder groups by changing the group number (or swapping groups if both groups have items). Pressing the number keys in the inventory gui switches items on the hotbar as usual.

With lots of items, it can be hard to track things and find what you're looking for. With this addition, you could group things by how frequently you use them, by type of item (redstone vs building blocks), or by world save, or as an overarching todo-list (grouped by which stage of the modpack you are in).

The controls are also backward compatible. If you don't want to use groups, you'll never know it existed. (that could also be interpreted as a bad thing)

**Sidenote:**
I kinda want to get into modding. I did a simple HelloWorld mod adding a block and a couple of items, but I'm more familiar with Python and Typescript than with Java. If you think this might be a relatively easy way to get familiar with Java and Fabric, I would be willing to contribute this feature. However, I've heard that Minecraft gui's can be a pain sometimes, so maybe this wouldn't be the best first contribution :joy: Let me know how difficult you think this would be.

**Comment by shedaniel** [comment] 2022-01-15 19:32
Duplicate of #388, Thanks for your suggestions on the keybinds though, that's something I haven't thought about.

**Closed as completed by shedaniel** 2022-01-15 19:32 UTC
Labels: status: duplicate, enhancement
