### ISSUE TITLE
Trying to change controls will crash the game

### ISSUE THREAD

**Issue by cs127** [shedaniel/RoughlyEnoughItems#252] opened 2020-01-22 15:22 UTC
Basically, while scrolling down the controls page, when it gets to the Roughly Enough Items section, the game crashes. I've tried it without using any other mods, it still crashes.
I have attached the crash report
[crash-2020-01-22_18.45.27-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/4098002/crash-2020-01-22_18.45.27-client.txt)

**Comment by shedaniel** [comment] 2020-01-22 15:38
Duplicate of #246

**Closed as completed by shedaniel** 2020-01-22 15:38 UTC
Labels: bug, status: duplicate, status: invalid
