### ISSUE TITLE
[Bug] REI Crashes with Ad Astra and other mods - Window 8320x8320 size out of bounds (max. size: 8192)

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [shedaniel/RoughlyEnoughItems#1411] opened 2023-05-20 06:56 UTC
### What happened?

When I open my inventory, REI starts loading, and that causes the game to crash.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://gist.github.com/ItsIgnacioPortal/3e436c8a8ed1c51a7d452b3ec1c21544
```

### Anything else?

Note that the issue doesn't happen if Ad Astra and REI are alone. It is likely that another mod is part of the culprit too.

Many of the mods are from [the Fabulously Optimized modpack](https://github.com/Fabulously-Optimized/fabulously-optimized). 

I've zipped my mods folder for easier testing of this bug: https://mega.nz/file/99hVGaAT#yhO0J97lU3AjG54-EOk9MS5rxIS77lgS7ZdMzRqOIb4

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by rozbrajaczpoziomow** [comment] 2023-05-20 07:14
The stacktrace is at line 4836 in the gist.

Also, there's this line just before the game fully crashes:
`[03:52:35] [Render thread/INFO]: [REI] Preparing cached texture with size 8320x8320 for 130x130 entries`

And REI crashes on [here](https://github.com/shedaniel/RoughlyEnoughItems/blob/10.x-1.19.3/runtime/src/main/java/me/shedaniel/rei/impl/client/gui/widget/CachedEntryListRender.java#L146):
`TextureTarget target = new TextureTarget(width, height, true, false);`

_From what I can tell in the stacktrace_, TextureTarget has a limit of 8192x8192, and because REI is trying to create a larger one, it just throws.

**Comment by ItsIgnacioPortal** [comment] 2023-05-20 22:20
> The stacktrace is at line 4836 in the gist.
> 
> Also, there's this line just before the game fully crashes:
> `[03:52:35] [Render thread/INFO]: [REI] Preparing cached texture with size 8320x8320 for 130x130 entries`
> 
> And REI crashes on [here](https://github.com/shedaniel/RoughlyEnoughItems/blob/10.x-1.19.3/runtime/src/main/java/me/shedaniel/rei/impl/client/gui/widget/CachedEntryListRender.java#L146):
> `TextureTarget target = new TextureTarget(width, height, true, false);`
> 
> _From what I can tell in the stacktrace_, TextureTarget has a limit of 8192x8192, and because REI is trying to create a larger one, it just throws.

Yeah I saw that but I don't know what to do about it. If I knew mod developing I'd add some sort of **print** statements so I could know what exactly it's trying to render that is so big.

**Comment by shedaniel** [comment] 2023-05-29 05:03
Duplicate of #1148

**Closed as not planned** 2023-05-29 05:03 UTC
Labels: bug, status: duplicate, priority: medium
