### ISSUE TITLE
[Bug] Polymorph bug

### ISSUE THREAD

**Issue by MCBEModder2020** [shedaniel/RoughlyEnoughItems#1439] opened 2023-07-01 01:44 UTC
### What happened?

[#47](https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/47)
it wont launch

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
look at [#47](https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/47)
```

### Anything else?

[#47](https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/47)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-07-01 08:17
Duplicate of the issue **you linked yourself**

**Closed as completed** 2023-07-01 08:17 UTC
Labels: bug
