### ISSUE TITLE
Game crashes when searching within REI

### ISSUE THREAD

**Issue by Sunekaer** [shedaniel/RoughlyEnoughItems#1202] opened 2022-11-08 17:31 UTC
### What happened?

Describe the bug

Game crashes every time you search for anything within REI.
Steps to reproduce

1.Set the game language to Simplified Chinese
2.open inventory tab
3.Type any text into REI's search box
4.game will crash

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://pste.me/@/u-WvlEvqIWw

There are 2 parts in the log

Crash itself https://pste.me/@/u70NKh6B7c0
But also this https://pste.me/@/iZDAyJKe3f4
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-11-08 17:56
Duplicate of #1199

**Closed as completed by shedaniel** 2022-11-08 17:56 UTC
Labels: bug, status: duplicate
