### ISSUE TITLE
[Bug] Keybinds register in search bar

### ISSUE THREAD

**Issue by TheFireOcean** [shedaniel/RoughlyEnoughItems#596] opened 2021-08-06 11:03 UTC
**Describe the bug**
Sometimes when trying to type in the search bar- actually most of the time, it registers keybinds and I end up closing my inventory.

**Steps to Reproduce**
- Try to type e in search bar

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
Forge 1.17

**Logs**
https://pastebin.com/F5Dk3zhj

**Comment by shedaniel** [comment] 2021-08-13 09:52
Duplicate of #594

**Closed as completed by shedaniel** 2021-08-13 09:52 UTC
Labels: bug, status: duplicate
