### ISSUE TITLE
[Bug] Game crash after favoriting any item

### ISSUE THREAD

**Issue by mcffbn** [shedaniel/RoughlyEnoughItems#535] opened 2021-05-15 18:30 UTC
**Describe the bug**
Game crashes after favoriting any item

**Steps to Reproduce**
- Favorite any item

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/05mA9rW6

**Additional context**

**Comment by shedaniel** [comment] 2021-05-15 18:34
Duplicate of #496

**Closed as completed by shedaniel** 2021-05-15 18:34 UTC
Labels: bug, status: duplicate
