### ISSUE TITLE
[Bug] Can't Hide Some of Kibes Items like Gliders via the Filtering System. 

### ISSUE THREAD

**Issue by StoneLegion** [shedaniel/RoughlyEnoughItems#696] opened 2021-12-28 22:12 UTC
**Describe the bug**
I'm using the Manual filter system to Hide Kibe's Gliders from showing up. Sadly everytime I go one page back it un-hides them and never lets me save it.

**Steps to Reproduce**
Add Kibe's to your game and go to manual filtering and try hiding all of kibe's Gliders. 

**Screenshots**
https://youtu.be/HHTxyygiSaA

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
Checked the Logs no loading errors nor an error when performing the actions. 

**Additional context**
RoughlyEnoughItems-7.1.357
kibe-1.9.4-BETA+1.18

**Comment by shedaniel** [comment] 2022-01-15 19:09
Duplicate of #667

**Closed as completed by shedaniel** 2022-01-15 19:09 UTC
Labels: bug, status: duplicate
