### ISSUE TITLE
[Bug] Issue with keybinds and creative search

### ISSUE THREAD

**Issue by MCBEModder2020** [shedaniel/RoughlyEnoughItems#1300] opened 2022-12-29 01:28 UTC
### What happened?

when using the creative mode search and pressing "r","u",or "a", while hovering over an item it brings up the popup for the item that you were hovering over and resets the creative mode search bar
please fix in 1.18.2

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
n/a
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-12-29 02:07
Duplicate of #58

**Closed as completed** 2022-12-29 02:07 UTC
Labels: bug, status: duplicate
