### ISSUE TITLE
Names not shown correctly

### ISSUE THREAD

**Issue by karstenzip** [shedaniel/RoughlyEnoughItems#564] opened 2021-06-21 16:43 UTC
**Describe the bug**
The names of the enderchest and all colors of the shulker boxes.
It shows up as item.minecraft.enderchest or item.minecraft.blue_shulker_box

**Screenshots**
![2021-06-21_18 35 48](https://user-images.githubusercontent.com/70335544/122797245-8bbdf280-d2bf-11eb-9e4d-39e92a8262be.png)
The same problem occures without the texture pack

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric 0.11.6

**Additional context**
I use the following mods (and versions):

- Slight GUI Modifications 2.0.0
- OptiFine G9 pre 21 (I know this is not a mod but still)
- Simple Voice Chat 1.1.5 
- Dynamic FPS 2.0.4
- Roughly Enough Items 6.0.254 alpha
- Shulkerboxtooltip 3.0.0 alpha 4
- Cloth Config 5.0.34
- TRansliterationLib 1.1.0
- Fabric API 0.36.0
- EditSign 2.2.1
- Voxelmap 1.10.15
- Architectury 2.0.10
- OptiFabric 1.11.9
- Not Enough Animations 1.3.0
- Mod Menu 2.0.2
- Not Enough Crashes 3.3.1
- Cloth API 2.0.54
- Where is it 1.12.6
- Entity Culling 1.3.0
All mods are for 1.17

**Comment by shedaniel** [comment] 2021-06-21 17:11
Unable to reproduce, please attach logs.

**Comment by karstenzip** [comment] 2021-06-21 17:15
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6688404/latest.log)
Do you mean this file?

**Comment by shedaniel** [comment] 2021-06-21 17:17
Duplicate of #517

**Closed as completed by shedaniel** 2021-06-21 17:17 UTC
Labels: bug, status: duplicate
