### ISSUE TITLE
[Bug] Crashing at startup for latest 1.18.2 version, when used alongside journeymap.

### ISSUE THREAD

**Issue by Warhand** [shedaniel/RoughlyEnoughItems#1134] opened 2022-09-25 00:09 UTC
### What happened?

The latest version of REI for 1.18.2 causes journeymap to crash on startup, and the issue is resolved by rolling back my version of REI to version 8.3.529.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Latest.log: https://gist.github.com/Warhand/0bacb8b030917cfd1d1845c6719ef9a2
Crash report: https://gist.github.com/Warhand/4efa7dfdc512cb4208c58be5bca459b8
```

### Anything else?

I tested the issue in a profile with the minimal amount of mods required and was still able to replicate the issue, the following is a full list of all mods used during testing, and their versions.

REI: 8.3.543
REI plugin compat: 8.0.7
Journeymap: 5.8.5
Cloth config API: 6.4.90
Architectury: 4.9.84
Forge: 40.1.71

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by thepriz** [comment] 2022-09-25 04:14
I can confirm that this broke in version 8.3.542 and is still broken in 8.3.543. It works fine with 8.3.529

**Comment by DenisMasterHerobrine** [comment] 2022-09-25 20:35
The same I can confirm for `9.1.546` for 1.19.2, reverting to `9.1.537` and REI Plugin Compatibilty to `9.0.8` solves this issue. Stacktrace is the same for OP. Sometimes it crashes a bit earlier and gets random stacktrace. Probably a random behaviour that makes this crash a bit harder to investigate, however most of the crash-reports are related to JM and REI Plugin Compatibilities. I hope this helps too.

**Comment by mysticdrew** [comment] 2022-09-27 21:37
This is happening due to a race condition with a recently added InputConstants.isKeyDown mixin in REI. I have applied a fix on my end, but it may be a while before the next JM release is published.

**Comment by shedaniel** [comment] 2022-09-28 09:25
Hey @mysticdrew, I feel like this is an issue best fixed in REI, I will make a fix later this day / week, thanks you for the fix on your end as well though!

**Closed as completed** 2022-09-28 09:27 UTC
Labels: bug

**Comment by mysticdrew** [comment] 2022-09-28 12:28
@shedaniel fair enough, it was old forge-fabric compatibility code on my end that was no longer needed so this forced me to do a needed cleanup anyways :)
