### ISSUE TITLE
[Feature] NBT Crafting support

### ISSUE THREAD

**Issue by Awakened-Redstone** [shedaniel/RoughlyEnoughItems#1077] opened 2022-08-16 19:13 UTC
### What is your feature request?

Currently **NBT Crafting** breaks the displaying of some recipes, making them not show on REI
It would be nice to have a compatibility with the mod, in the form as a plugin or as part of REI

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment] 2022-08-16 19:30
Duplicate of #357, implementing this is however unlikely.

**Closed as completed by shedaniel** 2022-08-16 19:30 UTC
Labels: status: duplicate, enhancement
