### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DaddySpin** [shedaniel/RoughlyEnoughItems#394] opened 2020-08-03 05:52 UTC
**Describe the bug**
It appears that when i had a item Favorited opening my inventory would crash my game and i had to open the REI config and remove the favorited item from the config and then i would crash some more and i have no idea how to recreate this, because after deleting my favorited items from the config again it seems fixed.

**Steps to Reproduce**
- no idea

**Environment:**
 - Minecraft: 1.16.1
 - Mod Loader: Fabric

**Logs**
Crash Log: https://pastebin.com/mHxrLBhU
Latest Log: https://pastebin.com/AnZczLpA

**Comment by shedaniel** [comment] 2020-08-03 07:28
Duplicate of #392 fixed already in v4.10.4

**Closed as completed by shedaniel** 2020-08-03 07:28 UTC
Labels: bug, status: duplicate
