### ISSUE TITLE
[Bug] REI search bar not working 1.18.2

### ISSUE THREAD

**Issue by Payback13** [shedaniel/RoughlyEnoughItems#1034] opened 2022-07-28 19:58 UTC
### What happened?

Whenever I go to search for anything using the REI search bar in game, it doesn't work. Nothing changes when I search and it doesn't look for the item. 
-Log-
https://gist.github.com/Payback13/beb2454c6acdeb9ce161e4a737b90e64 
![2022-07-28_14 55 09](https://user-images.githubusercontent.com/110194111/181625867-0e72cd1b-c1c4-45d2-bc12-cb2756091ba7.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Linked Above
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by zEpiixz** [comment] 2022-07-29 11:48
Same bug on Forge. However it only applies when i have another mod installed called Abnormals Delight. Everytime i shut it off in the modpack it works again. I dont know what weird interaction it is with mods but it might help finding the cause.

**Comment by Tralomine** [comment] 2022-07-29 20:40
same problem here on forge with abnormal delights, and to add to that, when trying to filter items, if searching anything it will crash because of `NullPointerException: Cannot invoke "net.minecraft.world.effect.MobEffect.m_19481_()" because "effect" is null` at `com.teamabnormals.abnormals_delight.common.item.NectarItem.m_7373_ (NectarItem.java:37)`, so it might be because of an invalid tooltip making the search index invalid (searching by mod, resource location or tag still works)
([full crash report](https://pastebin.com/xVPPB6AR))

**Comment by fzzyhmstrs** [comment] 2022-07-30 16:06
@Tralomine @zEpiixz your issues may be resolved per the closure of team-abnormals/abnormals-delight#46, once they put a new release out if they haven't already.

I don't think the original issue is resolved, however, because their modlist doesn't include Abnormal's Delights

**Comment by joshmcorreia** [comment] 2022-07-31 07:04
I'm facing the same issue, but I don't have Abnormals Delight installed.

**Comment by MaxNeedsSnacks** [comment] 2022-08-01 13:14
OP's issue stems from "Extra Generators", which apparently attempts to ~~render an additional hidden tooltip~~ (see below) directly when getting its tooltip lines. Since `EntryStack.getTooltip` is called from a worker thread (that's the `ForkJoinPool.commonPool-worker-12/INFO` part in the log), this will fail since you shouldn't be doing ~~render calls~~ (see below) off-thread.

EDIT: Need to correct myself, they're not actually rendering an additional tooltip, it's actually erroring attempting to log *an existing error* using Mojang's GL error util, as they try to check whether a certain key is down, which errors :P

Relevant log output
```
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Rendersystem called from wrong thread
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:181)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:170)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_4482(class_1041.java:222)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokePI(Native Method)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3409)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at net.minecraft.class_3675.method_15987(class_3675.java:465)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at io.github.lucaargolo.extragenerators.common.block.BlockCompendium.displayHiddenTooltip(BlockCompendium.kt:144)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at io.github.lucaargolo.extragenerators.common.block.BlockCompendium$registerBlockItems$1$1.method_7851(BlockCompendium.kt:90)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7950(class_1799.java:685)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:228)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:373)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.getTooltip(ForwardingEntryRenderer.java:55)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at me.shedaniel.rei.api.client.entry.renderer.EntryRendererRegistry$1.getTooltip(EntryRendererRegistry.java:55)
[14:22:58] [ForkJoinPool.commonPool-worker-12/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:212)
```

**Comment by shedaniel** [comment] 2022-08-01 13:23
@lucaargolo is it possible for you to add a thread check in Extra Generators before isKeyPressed? Doing RenderSystem.isRenderThread() is sufficient, or else I will need to mixin into stuff to fix this issue

**Comment by lucaargolo** [comment] 2022-08-02 05:41
Yeah sure, I can totally add it. On a side note, I've been playing with Extra Generators 1.2.1 and REI 8.3.510 (the same version from the first report) and everything is working fine in my modpack, so that might not be the real problem.

**Comment by DemonMartin** [comment] 2022-08-17 17:41
@lucaargolo, any plans when you'll update it? Got the same issues as this guy.

**Comment by shedaniel** [comment] 2022-09-17 18:45
Fix is coming, I will merge this issue with another one. Duplicate of #984

**Closed as completed by shedaniel** 2022-09-17 18:45 UTC
Labels: bug, status: duplicate

**Comment by seibarra** [comment] 2023-04-02 02:11
I fixed it in the REI options, inside "search" I changed asynchronous search to "no"

**Comment by stlouisn** [comment] 2023-09-24 22:55
still having to set asynchronous search to "no". without that change, REI cannot search, nor can you search using the creative tab

**Comment by shedaniel** [comment] 2023-09-29 17:36
If you can't search with the creative tab then maybe this is not exclusively REI's issue
