### ISSUE TITLE
[Bug] REI doesn't recognize resource pack/lang files?

### ISSUE THREAD

**Issue by Dejeh** [shedaniel/RoughlyEnoughItems#1348] opened 2023-02-02 08:28 UTC
### What happened?

Selecting resource packs with lang files changes the name of items in the REI menu, but doesn't allow you to search the item up using that name.

This seems like it should have been noticed by now. Am I missing something?

### What mod loaders are you seeing the problem on?

Fabric, Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
.
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-02-08 17:58
Try rejoining the world after changing refresh packs, or going into `REI Config > Advanced > Reset Search`

**Comment by shedaniel** [comment] 2023-03-10 17:42
I will close this issue, please reopen if this is actually caused by REI

**Closed as not planned** 2023-03-10 17:43 UTC
Labels: bug, note: pending question
