### ISSUE TITLE
[Bug] Weird refined storage bug

### ISSUE THREAD

**Issue by Joly0** [shedaniel/RoughlyEnoughItems#1223] opened 2022-11-17 20:16 UTC
### What happened?

If i open the refined storage terminal and search something there, i cant open recipes in rei afterwards. If i click an item, nothing happens. I have to close the terminal and can then reopen it and am able to click items in rei again and see their recipes

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Nothing useful there
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by rozbrajaczpoziomow** [comment] 2022-11-17 21:01
I think I reported this like half an hour before

**Comment by shedaniel** [comment] 2022-11-17 23:17
Duplicate of shedaniel/REIPluginCompatibilities-Issues/issues/27

**Closed as completed by shedaniel** 2022-11-17 23:17 UTC
Labels: bug, status: duplicate
