### ISSUE TITLE
[Forge 1.20.1] [Bug] Strange crash with Architectury.

### ISSUE THREAD

**Issue by vizthex123** [shedaniel/RoughlyEnoughItems#1623] opened 2024-04-28 02:52 UTC
### What happened?

My game would randomly crash. Wasn't sure why, so I asked the CurseForge discord for help and someone there said it was "something with REI and Architectury".

I can mirror this issue to them if needed.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [x] Plugin Integration / JEI Plugin Compatibility
- [x] Others

### Relevant log output

```shell
Caused by: java.lang.IllegalArgumentException: fromIndex(117) > toIndex(107)
    at java.util.AbstractList.subListRangeCheck:L509
    at java.util.ArrayList.subList:L1108
    at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.updateEntries:L138
    at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateEntriesPosition:L265
    at me.shedaniel.rei.impl.client.gui.widget.entrylist.CollapsingEntryListWidget.updateEntriesPosition:L67
    at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateArea:L250
    at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.init:L177
    at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_88315_:L225
    at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render:L375
    at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5:L91
    at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1:L61
    at dev.architectury.event.forge.EventHandlerImplClient.eventContainerScreenEvent:L153
    at dev.architectury.event.forge.__EventHandlerImplClient_eventContainerScreenEvent_Background.invoke:dynamic
```

### Anything else?

Here's the entire log just in case:
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/15140606/latest.log)

I've got this and Architectury installed on 2 modpacks with the same versions of each mod, Forge, and Minecraft - but only this one is crashing.

I think it might be some kind of strange conflict with AE2 or Thermal Dynamics, as it only crashes when I look at my ME System after closing the Deep Learner.

I've also customized REI with multiple filters and collapsible entries (as well as re-arranging the crafting category tabs), so that might be contributing to it?

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2024-04-29 15:43
Duplicate of #1614

**Closed as completed by shedaniel** 2024-04-29 15:43 UTC
Labels: bug, status: duplicate
