### ISSUE TITLE
Could not create REI Plugin

### ISSUE THREAD

**Issue by Viching666** [shedaniel/RoughlyEnoughItems#1298] opened 2022-12-27 16:40 UTC
### What happened?

Could not create REI Plugin [REIPlugin] due to errors, provided by 'vinery'!
Fabric 1 18 2 
![Screenshot_9](https://user-images.githubusercontent.com/93470213/209695580-dbef5b75-7322-4d9a-b3eb-9caf5ebc360c.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [x] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
idk
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-12-27 18:34
Duplicate of #1284

This is caused by Vinery, please report the issue to them

**Closed as not planned by shedaniel** 2022-12-27 18:34 UTC
Labels: bug, status: duplicate, status: invalid, other mods, env: fabric
