### ISSUE TITLE
[Bug] (Fabric) Villager-style gui entries *don't handle multiple outputs well

### ISSUE THREAD

**Issue by supersaiyansubtlety** [shedaniel/RoughlyEnoughItems#653] opened 2021-11-07 02:55 UTC
**Describe the bug**
The REI plugin I'm writing somehow cause REI's villager-style gui entries to become too tall, and for their stack entries to stop cycling and instead render all stacks on top of one another. 

**Steps to Reproduce**
- Checkout this branch of my project https://gitlab.com/supersaiyansubtlety/anvil_crushing_recipes/-/blob/REI-bug/src/main/java/net/sssubtlety/anvil_crushing_recipes/rei/AnvilCrushingCategory.java

- Launch the game and look at my REI entries (I made a bunch of test recipes for with colors of terracotta as input)

**Screenshots**
![anvil crushing REI](https://user-images.githubusercontent.com/618276/140630344-2bf854f7-3dfb-4d1b-9f07-fcccb6c5cb7c.png)

**Environment:**
 - Minecraft: 1.17.1
 - Mod Loader: fabric, 0.12.3
 - REI: 6.0.307-alpha
 - FAPI: 0.41.0+1.17

**Logs**
[latest.log](https://pastebin.com/hA8E7UZa)
[rei-log](https://pastebin.com/5pg6ySc6)

**Comment by supersaiyansubtlety** [comment] 2021-11-07 03:04
This is the test datapack I mentioned. 
[output_op_combo_terracotta_test.zip](https://github.com/shedaniel/RoughlyEnoughItems/files/7491634/output_op_combo_terracotta_test.zip)

**Comment by supersaiyansubtlety** [comment] 2021-11-15 21:28
It seems as though the issue is just that multiple outputs from `me.shedaniel.rei.api.common.display.Display::getOutputEntries` are rendered on top of one another, and yet the villager gui list item is stretched vertically to fit the number of output entries (if they were spaced out vertically).

**Comment by shedaniel** [comment] 2022-01-15 19:13
Duplicate of #617

**Closed as completed by shedaniel** 2022-01-15 19:13 UTC
Labels: bug
