### ISSUE TITLE
[Bug] Game crashes when you try to use the searchbar. (1.18.1)(Fabric)

### ISSUE THREAD

**Issue by Joulanh** [shedaniel/RoughlyEnoughItems#763] opened 2022-02-06 11:55 UTC
### What happened?

Game crashes when you try to type in the searchbar.
REI version 7.2.425
Farbic Launcher 0.13.1
Fabric api 0.46.4+1.18

The added files are the reports copied into the relevant log output 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// There are four lights!

Time: 06/02/2022, 12:44
Description: Saving entity NBT

java.lang.ClassCastException: class net.minecraft.class_638 cannot be cast to class net.minecraft.class_3218 (net.minecraft.class_638 and net.minecraft.class_3218 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @14acaea5)
	at dev.mrsterner.guardvillagers.common.entity.GuardEntity.method_5652(GuardEntity.java:334)
	at net.minecraft.class_1297.method_5647(class_1297.java:1653)
	at io.github.queerbric.inspecio.tooltip.SpawnEntityTooltipComponent.of(SpawnEntityTooltipComponent.java:78)
	at net.minecraft.class_1826.method_32346(class_1826.java:544)
	at net.minecraft.class_1799.method_32347(class_1799.java:104)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:351)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.getTooltip(ForwardingEntryRenderer.java:48)
	at me.shedaniel.rei.api.client.entry.renderer.EntryRendererRegistry$1.getTooltip(EntryRendererRegistry.java:54)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:208)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.mrsterner.guardvillagers.common.entity.GuardEntity.method_5652(GuardEntity.java:334)
	at net.minecraft.class_1297.method_5647(class_1297.java:1653)
	at io.github.queerbric.inspecio.tooltip.SpawnEntityTooltipComponent.of(SpawnEntityTooltipComponent.java:78)
	at net.minecraft.class_1826.method_32346(class_1826.java:544)
	at net.minecraft.class_1799.method_32347(class_1799.java:104)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:351)

-- Entity being saved --
Details:
	Entity Type: guardvillagers:guard (dev.mrsterner.guardvillagers.common.entity.GuardEntity)
	Entity ID: 469
	Entity Name: Guard
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_5647(class_1297.java:1653)
	at io.github.queerbric.inspecio.tooltip.SpawnEntityTooltipComponent.of(SpawnEntityTooltipComponent.java:78)
	at net.minecraft.class_1826.method_32346(class_1826.java:544)
	at net.minecraft.class_1799.method_32347(class_1799.java:104)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:351)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.getTooltip(ForwardingEntryRenderer.java:48)
	at me.shedaniel.rei.api.client.entry.renderer.EntryRendererRegistry$1.getTooltip(EntryRendererRegistry.java:54)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:208)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Fabric Mods: 
		additionalbars: Additional Bars 2.2.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancedcompass: Advanced Compass 1.2.6
		advancementinfo: AdvancementInfo 1.18-fabric0.43.1-1.3
		antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 3.6.16
		bclib: BCLib 1.3.0
		betterend: Better End 1.0.2
		bettermounthud: Better Mount HUD 1.1.3
		betternether: Better Nether 6.0.10
		blockmeter: Block Meter 1.6
		blue_endless_jankson: jankson 1.2.1
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.0
		cardinal-components-entity: Cardinal Components API (entities) 4.1.0
		chipped: Chipped 1.2
		clientcommands: Client Commands 2.6
		clientcommands-scripting: Clientcommands Scripting 1.3
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.50
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.1-1.18.1
		connectiblechains: Connectible Chains 2.0.1+1.18.1
		continuity: Continuity 1.0.3+1.18
		copperhopper: Copper Hopper 0.0.2+1.18.1
		cosmetic-armor: Cosmetic Armor 1.2.0
		couplings: Couplings 1.7.1+1.18
		crowdin-translate: CrowdinTranslate 1.4+1.18
		doublejump: Double Jump Mod 1.0.1+mc1.18
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49c-fabric
		edenring: EdenRing 0.3.0
		enchantinginfuser: Enchanting Infuser 3.1.0
		entityculling: EntityCulling-Fabric 1.4.0
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.1
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		fiber: fiber 0.23.0-2
		forgeconfigapiport: Forge Config API Port 3.1.0
		full_slabs: FullSlabs 3.3.3
		gameblocks: Gameblocks 0.1.0-beta+1.18.1
		geckolib3: Geckolib 3.0.32
		goldenhoppers: Golden Hoppers 1.2.0
		graveyard: The Graveyard 1.5
		guardvillagers: Guard Villagers Fabric 1.0.2
		homebodies_fantasy: Homebodies: Fantasy 1.0.0
		horseinfo: Horse Info 0.4.0-1.18
		iceberg: Iceberg 1.0.38
		impaled: Impaled 1.0.2
		indium: Indium 1.0.2-alpha2+mc1.18.1
		inmis: Inmis 2.4.0-1.18
		inspecio: Inspecio 1.2.1+1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.1-1.18
		invisframes: Invisible Frames 2.1.0
		iris: Iris 1.2.0-pre
		itemscroller: Item Scroller 0.15.0
		jankson: Jankson 4.0.0+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		krypton: Krypton 0.1.6
		kyrptconfig: Kyrpt Config 1.2.5-1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.2.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lightoverlay: Light Overlay 6.0.4
		litematica: Litematica 0.9.0
		lithium: Lithium 0.7.7
		llamarama: Llamarama 1.5.2
		magic_mirror: Magic Mirror 1.3.3b
		malilib: MaLiLib 0.10.0-dev.26
		micalibria: Micalibria 2.0.0
		minecraft: Minecraft 1.18.1
		minihud: MiniHUD 0.19.0-dev.20211204.230657
		mobscarecrow: Mob Scarecrow 1.1.0
		modmenu: Mod Menu 3.0.1
		multibeds: MultiBeds 1.2.0
		multiconnect-api: MultiConnect API 1.5
		musica: Musica 1.5.0
		myron: Myron 1.6.1-1.17.1
		mythic-mounts: Mythic Mounts 1.18-4.0
		nicephore: Nicephore fabric-1.18.x-1.1.1
		omega-config: OmegaConfig 1.2.2-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		paintings: Paintings++ 1.0.0.6
		pandamc_concreteplus: Concrete Plus 1.9.2
		patchouli: Patchouli 1.18.1-62-FABRIC
		phonos: Phonos 0.2+1.18
		phosphor: Phosphor 0.8.1
		pride: Pride Lib 1.1.0+1.17
		puzzleslib: Puzzles Lib 3.1.2
		roughlyenoughitems: Roughly Enough Items 7.2.425
		shetiphiancore: ShetiPhianCore 1.2.1
		sign_editor: Better Signs & Frames 0.8.3
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.3.9
		spruceui: SpruceUI 3.3.0+1.17
		statement: Statement 4.2.1+1.14.4-1.18.1
		statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.0.0
		trinkets: Trinkets 3.1.0
		tweakeroo: Tweakeroo 0.11.0
		veinmining: Vein Mining 0.0.11-1.18
		voicechat: Simple Voice Chat 1.18.1-2.1.28
		worldedit: WorldEdit 7.2.8+6008-1246d61
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 22.1.2
		xaeroworldmap: Xaero's World Map 1.20.1
		yigd: You're in Grave Danger 1.2.8B
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8010094/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8010095/rei.log)
[crash-2022-02-06_12.44.56-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/8010096/crash-2022-02-06_12.44.56-client.txt)

**Comment by shedaniel** [comment] 2022-02-06 11:56
Duplicate of #740

**Comment by shedaniel** [comment] 2022-02-06 11:57
Please search before your report an issue for whether it has been reported already, my god

**Closed as completed** 2022-02-06 11:56 UTC
Labels: bug, status: duplicate

**Comment by Joulanh** [comment] 2022-02-06 14:00
sry for the inconvinience. The other bug report title is really specific and there was nothing showing when i searched for search bar.
