### ISSUE TITLE
[Bug] The latest rei [FORGE] don't show some recipe

### ISSUE THREAD

**Issue by Foxsyl** [shedaniel/RoughlyEnoughItems#827] opened 2022-04-05 21:41 UTC
### What happened?

some recipe of tinkers construck won't show if i click

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
this is big i upload this in section below "Anything else?"
```

### Anything else?

smeltery recipe not show
and black boo
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8422019/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8422020/rei.log)
k

**Comment by shedaniel** [comment] 2022-04-08 17:46
Can you give more details on what recipes you aren't able to look at?

**Comment by Foxsyl** [comment] 2022-04-08 21:50
Smeltery from tinkers construct 1.18.1
And 1 book
![16494544822494195576265843910851](https://user-images.githubusercontent.com/101817446/162536523-092e34fe-ff5e-450a-bc14-9cfc926816cd.jpg)
![16494545037892542740321855479033](https://user-images.githubusercontent.com/101817446/162536574-48ed2030-9ae6-4558-acae-1f5bfc277dc8.jpg)
![16494545171806269729210741048253](https://user-images.githubusercontent.com/101817446/162536609-d9904ea7-869a-4431-834c-028e4797eae8.jpg)
I now find this 3 not working but Maybe is more

Dont worry about missing texture I have shaders turn on and it sometimes happend

**Comment by shedaniel** [comment] 2022-04-09 05:03
Duplicate of #818

**Closed as completed** 2022-04-09 05:03 UTC
Labels: bug, status: duplicate, note: pending question
