### ISSUE TITLE
[Bug] 1.20 game crash

### ISSUE THREAD

**Issue by Doctor-Keller** [shedaniel/RoughlyEnoughItems#1485] opened 2023-08-20 20:50 UTC
### What happened?

The game crashes after any interaction with fluids in AE2 terminals. Even after just pressing any key while hovering mouse cursor over them.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://gist.github.com/Doctor-Keller/c80c076c51a6a2e335731898694230fe
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by mvojacek** [comment] 2023-08-22 12:15
The same exception (`Failed to find EntryType of ClickableIngredient[ingredient=me.shedaniel.rei.plugincompatibilities.xxx`) is also thrown when interacting with with entries in the crafting terminal's crafting monitor screen (the top right hammer icon). Not only clicking it, but also pressing any key while hovering over them triggers the exception, which is quite annoying when closing the window using Esc and hovering inside the window.

Updated to latest versions (AE2 15.0.9-beta, REI 12.0.645, REIPC 12.0.55) and still happens.

Please at least catch the exception so it doesn't crash the game when interacting with unimplemented/broken guis.

**Comment by mvojacek** [comment] 2023-08-22 12:23
Also happens when pressing the 'View Recipe' bind while hovering over an ingredient with 65+ stack size while encoding a processing pattern in the pattern terminal.

**Comment by shedaniel** [comment] 2023-08-25 17:30
Duplicate of https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/49

**Closed as not planned** 2023-08-25 17:31 UTC
Labels: bug, status: duplicate
