### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by JackyMaelstrom** [shedaniel/RoughlyEnoughItems#957] opened 2022-06-27 18:09 UTC
### What happened?

Running REI+RER alongside Tinkers' Construct and Tinkers' Reforged (along with all required parents/dependencies), version 1.18.2. After turning on/off the mods, it looks to be a conflicting issue between RER and Tinkers' Reforged not being compatible. The error screen is as below:

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.material.FlowingFluid.m_76068_(boolean)" because the return value of "net.minecraft.world.level.block.LiquidBlock.getFluid()" is null
Exit Code: -1

It looks like someone else already had a similar crash error, however their issue seemed to be different.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/27/22, 2:07 PM
Description: Rendering overlay

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.material.FlowingFluid.m_76068_(boolean)" because the return value of "net.minecraft.world.level.block.LiquidBlock.getFluid()" is null
	at net.minecraft.world.level.block.LiquidBlock.initFluidStateCache(LiquidBlock.java:181) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.LiquidBlock.m_5888_(LiquidBlock.java:89) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60819_(BlockBehaviour.java:771) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
	at net.minecraft.world.level.block.LiquidBlock.m_5939_(LiquidBlock.java:68) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase$Cache.<init>(BlockBehaviour.java:837) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java:454) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:518) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.21.jar%2362!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.21.jar%2362!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.21.jar%2362!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.21.jar%2362!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$finishModLoading$6(ClientModLoader.java:127) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:113) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.finishModLoading(ClientModLoader.java:127) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$3(ClientModLoader.java:106) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.level.block.LiquidBlock.initFluidStateCache(LiquidBlock.java:181) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.LiquidBlock.m_5888_(LiquidBlock.java:89) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60819_(BlockBehaviour.java:771) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
	at net.minecraft.world.level.block.LiquidBlock.m_5939_(LiquidBlock.java:68) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase$Cache.<init>(BlockBehaviour.java:837) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java:454) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:518) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.21-universal.jar%2365!/:?] {re:classloading,pl:epic_rei_lmao:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.21.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 876800056 bytes (836 MiB) / 2883584000 bytes (2750 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 44772.01
	Virtual memory used (MB): 26993.52
	Swap memory total (MB): 28487.73
	Swap memory used (MB): 3403.17
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Launched Version: forge-40.1.21
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.9664, Intel
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TConstruct-1.18.2-3.5.1.31.jar                    |Tinkers' Construct            |tconstruct                    |3.5.1.31            |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-8.2.492.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |8.2.492             |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughProfessions-forge-1.18.2-1.0.1.jar   |Roughly Enough Professions    |roughlyenoughprofessions      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.62-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.62              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.21-universal.jar                |Forge                         |forge                         |40.1.21             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Tinkers Reforged 1.18.2-1.0.7b.jar                |Tinkers Reforged              |tinkers_reforged              |1.0.7b              |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.27.jar                          |Mantle                        |mantle                        |1.9.27              |DONE      |Manifest: NOSIGNATURE
		architectury-4.5.75-forge.jar                     |Architectury                  |architectury                  |4.5.75              |DONE      |Manifest: NOSIGNATURE
		rer-2.5.1.jar                                     |Roughly Enough Resources      |roughlyenoughresources        |2.5.1               |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-jei-internals-workaround-8.2.49|REI Internals Workaround      |rei_internals_workaround      |8.2.492             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e3e9f4db-e6d7-430b-aa4d-0799a37eaab0
	FML: 40.1
	Forge: net.minecraftforge:40.1.21
```

**Comment by shedaniel** [comment] 2022-06-27 18:15
Duplicate of https://github.com/theorbtwo/RoughlyEnoughResources/issues/63

**Closed as completed by shedaniel** 2022-06-27 18:15 UTC
Labels: bug, status: duplicate
