### ISSUE TITLE
[Bug] search box renders over Item tooltips

### ISSUE THREAD

**Issue by EGOIST1372** [shedaniel/RoughlyEnoughItems#835] opened 2022-04-17 14:18 UTC
### What happened?

Title + 3 screenshots

![image](https://user-images.githubusercontent.com/86555131/163718366-9d86f580-a762-454b-8e0f-8b961379d1ba.png)

![2022-04-17_18 12 13](https://user-images.githubusercontent.com/86555131/163718295-26c7d45f-078a-4a7a-a145-3fa33ed2b84a.png)

and here even the text "search" in search box is weird too

![2022-04-17_18 19 32](https://user-images.githubusercontent.com/86555131/163718394-753ecaf4-3af0-41e1-9158-35ec98ffbe0c.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
none
```

**Comment by shedaniel** [comment] 2022-05-27 10:51
Duplicate of #835

**Comment by EGOIST1372** [comment] 2022-05-31 12:15
@shedaniel Sorry to bother you but you marked this as duplicate of #835 but this issue is #835
how my issue is duplicate of my issue? I'm confused

**Comment by shedaniel** [comment] 2022-05-31 22:36
Sorry lmao

**Closed as completed** 2022-11-12 07:57 UTC
Labels: bug, type: visual
