### ISSUE TITLE
[Bug] [BYG Compat] Items stacks double in quantity when viewing the recipe (R) of an item in a chest

### ISSUE THREAD

**Issue by ChristopherHaws** [shedaniel/RoughlyEnoughItems#1252] opened 2022-11-30 08:45 UTC
### What happened?

I am noticing a weird bug on my server where the item stacks that contain items from BYG (oh the biomes you'll go) inside of a chest double in size every time I hit R to view the recipe of an item in the chest and then E to go back to the chest. It is not actually duplicating the items though. If you close the chest or try to take any of the items it updates based on the values the server knows them to be.

This only seems to be happening for BYG items. I also have create mod installed and it is not happening for items from that mod.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
It isn't logging anything when I do this
```

### Anything else?

![image](https://user-images.githubusercontent.com/5934505/204748165-f2ea0c8e-a8d6-432e-b584-db6a1bf333c5.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-12-18 06:58
Duplicate of #486

**Closed as completed by shedaniel** 2022-12-18 06:58 UTC
Labels: bug, status: duplicate, priority: high
