### ISSUE TITLE
Extreme FPS drops when REI shown [Bug]

### ISSUE THREAD

**Issue by ijlx** [shedaniel/RoughlyEnoughItems#380] opened 2020-07-13 08:44 UTC
**Describe the bug**
When REI is shown in inventory menus, FPS drops heavily to around 30 from ~120.

**Steps to Reproduce**
- Open your inventory.
- FPS should drop.
- Hide REI with Ctrl-o.
- FPS should return.

**Screenshots**
With REI shown:
![](https://i.imgur.com/14GZox1.png)

With REI closed via ctrl-o:
![](https://i.imgur.com/jMTwlGN.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: Fabric

**Logs**
https://paste.ee/p/JkSPg

**Comment by ijlx** [comment] 2020-07-13 08:54
This bug does not occur in the usage and recipe menus.

**Comment by shedaniel** [comment] 2020-07-13 10:20
rendering items are expansive, try increasing the entry size in the accessibility to reduce the amount of items

**Comment by shedaniel** [comment] 2020-07-18 07:39
Duplicate of #158

**Closed as completed by shedaniel** 2020-07-18 07:39 UTC
Labels: bug
