### ISSUE TITLE
[Bug] Broken item display when enabled caching

### ISSUE THREAD

**Issue by whitebear60** [shedaniel/RoughlyEnoughItems#1315] opened 2023-01-08 10:08 UTC
### What happened?

When I toggled on Miscellaneous - Caching Entity Rendering, the REI screen is messed up with item icons. When I press F3+T to reload resources, then everything is back to normal until I start searching for something, on search the icons are messed up again.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10368115/latest.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10368116/rei-issues.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10368117/rei.log)

### Anything else?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/42472132/211190126-f31e3eb8-a69b-446d-b20b-a9317298107b.png">

REI 10.0.581
Architectury 7.0.66
Fabric 0.14.12
Minecraft 1.19.3
macOS 13.0.1
MacBook Pro 2017

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-01-08 10:30
Duplicate of #1271

**Closed as completed** 2023-01-08 10:30 UTC
Labels: bug, status: duplicate
