### ISSUE TITLE
Expose Filtering Rules as API

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [shedaniel/RoughlyEnoughItems#1149] opened 2022-10-11 01:32 UTC
### What is your feature request?

Currently, the only way for a plugin to "remove" an entry is to remove it from the entry registry. Unlike what may seem intuitive for people coming from a mod like JEI, this *does not* also remove the target entry from the list of entry ingredients (for example, the cycling stacks in recipe displays), since the entry registry really just represents the user-facing display on the side of the inventory screen.

One possible solution for keeping this split intact while also allowing addon devs to actually properly *hide* things from REI entirely (including as ingredients in displays) would be to expose the currently internal concept of Filtering Rules as public API. From a cursory glance, this definitely seems doable, though internals would have to be changed significantly to not just differentiate between the existing two types of filtering rules, but to allow for a more general distinction between custom "fixed" default filtering rules (which would in turn fully "hide" the ingredient from view) and dynamic filtering (e.g through search)

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by rlnt** [comment] 2022-10-11 20:38
The cycling issue mentioned in this is what's displayed here https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/13

**Comment by shedaniel** [comment] 2022-10-21 15:39
Duplicate of https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/13
EDIT: I am blind

**Closed as completed** 2022-10-28 12:05 UTC
Labels: enhancement
