### ISSUE TITLE
Not showing blocks in inventory

### ISSUE THREAD

**Issue by slezaCZ** [shedaniel/RoughlyEnoughItems#758] opened 2022-02-05 11:24 UTC
### What happened?

Idk why but my block just wont show up in inventor
![Snímek obrazovky 2022-02-05 122432](https://user-images.githubusercontent.com/96537476/152640065-e9778d47-5327-43ec-98aa-c21d95430d5a.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by Azazelrus** [comment] 2022-02-05 11:29
Try updating Architecture API

**Comment by shedaniel** [comment] 2022-02-05 11:29
Please attach more info to your bug report

**Comment by slezaCZ** [comment] 2022-02-05 11:31
its like there. if i hold left mouse it shows me names of the blocks but wont show icons

**Comment by shedaniel** [comment] 2022-02-05 11:36
Duplicate of #756

**Closed as completed by shedaniel** 2022-02-05 11:36 UTC
Labels: bug, status: duplicate
