### ISSUE TITLE
[Bug] Enchanted books cannot be searched after installing REI

### ISSUE THREAD

**Issue by Spturate** [shedaniel/RoughlyEnoughItems#1673] opened 2024-06-25 13:21 UTC
### What happened?

Regarding the search for 1.21, I can't find a specific enchanted book, 1.20.1 and vanilla have no problem using REI
Fabric version:0.15.11
Fabric API :0.100.3
REI version:16.0.729
Architectury API:13.0.2
Cloth Config API:15.0.127
![屏幕截图 2024-06-25 210617](https://github.com/shedaniel/RoughlyEnoughItems/assets/30800649/9bb9f41d-36aa-4e9c-9a84-3023a68f5c50)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[latest.log](https://github.com/user-attachments/files/15971968/latest.log)
[rei.log](https://github.com/user-attachments/files/15971970/rei.log)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ewe2** [comment] 2024-06-30 04:02
All books can only be seen in Creative mode, in survival there is only 1 book to be seen in Collapsible groups and general.

**Comment by shedaniel** [comment] 2024-08-14 06:12
Duplicate of #1666

**Closed as completed by shedaniel** 2024-08-14 06:12 UTC
Labels: bug, status: duplicate
