### ISSUE TITLE
[Bug] The button to copy a recipe from REI into a crafting table stops working when Lithium is installed. Fabric 1.19.2

### ISSUE THREAD

**Issue by Halex000** [shedaniel/RoughlyEnoughItems#1506] opened 2023-09-27 08:02 UTC
### Version Information

RoughlyEnoughItems-9.1.657

### Expected Behavior

The + button should copy the recipe from the REI recipe menu to the crafting table.
![270902441-eda72387-fd4d-498c-b173-803b5d728560](https://github.com/shedaniel/RoughlyEnoughItems/assets/95841600/179d76c3-8136-49c3-861e-3a6e2d8cd5d8)
![270902471-6e5f4d5c-f1d5-4748-8579-e5b7f9943041](https://github.com/shedaniel/RoughlyEnoughItems/assets/95841600/a205d366-320c-4ea7-9ccc-d41a1e527adb)

### Actual Behavior

The + button copies the recipe over to the crafting table incorrectly. This occurs for all vanilla and modded recipes.
![270902834-3edee902-7dd4-474a-abf6-5119824bca02](https://github.com/shedaniel/RoughlyEnoughItems/assets/95841600/29c3e889-702e-456f-a239-c475b0629579)

### Reproduction Steps

1. Install Lithium, I am using Lithium-fabric-mc1.19.2-0.11.1. I am also using the mods found below. 
I performed a binary search on my mod list until I identified Lithium as the cause for this bug.
![270903488-d292544b-ad09-4287-819f-dce89c20ab02](https://github.com/shedaniel/RoughlyEnoughItems/assets/95841600/5b60e337-6a15-4ba9-a151-7405d9fe5447)

2. Place a crafting table and get the materials for a crafting recipe in your inventory, it can be any recipe.

3. Search for the recipe in REI and click the plus button in the GUI to load it into the crafting table.

The recipe should be loaded incorrectly with Lithium installed.

### Other Information

Bug performed in fabric for 1.19.2

Mods used to recreate bug:
![270904394-a975249f-712d-4bd5-83c4-5cf00778a78f](https://github.com/shedaniel/RoughlyEnoughItems/assets/95841600/60257bae-7f19-4a04-8ceb-c8d214490c50)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
None
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by MDMCK10** [comment] 2023-09-29 15:50
Duplicate of #1492

**Comment by shedaniel** [comment] 2023-09-29 17:28
Duplicate of #1492

**Closed as not planned** 2023-09-29 17:28 UTC
Labels: bug, status: duplicate
