### ISSUE TITLE
Minecraft crashes when you open inventory with REI

### ISSUE THREAD

**Issue by ju1ian4** [shedaniel/RoughlyEnoughItems#750] opened 2022-01-30 18:38 UTC
When I have REI installed for fabric and I open my inventory when in a server, the game crashes. I'm assuming it's because it's trying to load all the items on the side of the screen.

"The game crashed whilst rendering screen 
Error: java.lang.NoSuchFieldError: field_2900 
Exit Code: 255"

- Minecraft 1.18.1
 - Mod Loader: Fabric

When I remove REI from my mods folder, everything works fine. However, I need REI to view crafting recipes from a weapons mod I'm using. Any help is appreciated.

**Comment by itsdinkd** [comment] 2022-01-30 20:28
post logs

**Comment by Panderine** [comment] 2022-01-31 23:58
Same crash.

Here's the log
https://paste.ee/p/SP30h

**Comment by shedaniel** [comment] 2022-02-01 08:01
Duplicate of #740

**Closed as completed by shedaniel** 2022-02-01 08:01 UTC
Labels: bug, status: duplicate
