### ISSUE TITLE
[Bug] Crash when too many entries to cache

### ISSUE THREAD

**Issue by TexBlock** [shedaniel/RoughlyEnoughItems#1294] opened 2022-12-23 07:46 UTC
### What happened?

In FTB StoneBlock 3, open the inventory crash.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/TexBlock/db9f684dbef7425e7f221f0da47936dd
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by BuddhaBuddy1** [comment] 2022-12-23 20:44
Also getting this. It happens every time if you try to open anything that has an inventory while REI is still loading. I have to make sure I don't try to look at my character's inventory, my storage system, crate, pouch, etc, for at least 10 seconds after loading a game. This has been happening since Stoneblock 3 came out, so wasn't introduced by any recent changes. I just never thought to report it until now.

I'll attach my crash report, but the relevant lines in the stack trace are:
```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:?] {}
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl.getFocusedStack(ScreenRegistryImpl.java:144) ~[RoughlyEnoughItems-8.3.583.jar%23230!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
```

I don't know what the OP's gist is, but it doesn't appear to be a crash report, and seems to cut off too early.

Hmm, can't attach .txt or .zip files?

[crash-2022-12-23_12.18.57-client_.txt](https://gist.github.com/BuddhaBuddy1/4738adfb11904eae3708b0b689f2ac6b)

---
Edit to add that when this happens, there is a warning dialog from REI stating that it is still loading, so it seems that REI knows it isn't ready yet, but still something fatal happens.

**Comment by papillo12** [comment] 2022-12-24 03:58
[crash-2022-12-23_21.54.57-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/10297951/crash-2022-12-23_21.54.57-client.txt)
 same but for fabric 1.19.2

**Comment by TexBlock** [comment] 2022-12-24 06:25
Turning off `Caching Entry Rendering` can solve this problem temporarily.

**Comment by papillo12** [comment] 2022-12-24 06:39
> Turning off `Caching Entry Rendering` can solve this problem temporarily.

Where do I do that?

**Comment by TexBlock** [comment] 2022-12-24 06:44
> > Turning off `Caching Entry Rendering` can solve this problem temporarily.
> 
> Where do I do that?

REI Config -> Advanced -> Miscellaneous -> Caching Entry Rendering

**Comment by shedaniel** [comment] 2022-12-24 09:19
@BuddhaBuddy1 can you create a separate issue for yours? would be great!

**Comment by BuddhaBuddy1** [comment] 2022-12-24 22:41
> @BuddhaBuddy1 can you create a separate issue for yours? would be great!

Sure, created [[Bug] REI Crash opening any Inventory while REI is still initializing](https://github.com/shedaniel/RoughlyEnoughItems/issues/1295)

**Comment by shedaniel** [comment] 2022-12-27 18:41
@papillo12 Your issue is a different issue from @TexBlock, and I have created another issue #1299 to track it instead

@TexBlock Your logs does not include a crash, do you have a crash report instead?

**Comment by TexBlock** [comment] 2022-12-27 22:56
> @TexBlock Your logs does not include a crash, do you have a crash report instead?

uploaded crash report

**Comment by shedaniel** [comment] 2022-12-29 03:33
Thank you for confirming it!

**Comment by shedaniel** [comment] 2023-05-30 04:13
Duplicate of #1148

**Closed as not planned by shedaniel** 2023-05-30 04:13 UTC
Labels: bug, status: duplicate, priority: medium, note: confirmed
