### ISSUE TITLE
[Bug] Game crash when loading a world

### ISSUE THREAD

**Issue by th3heindnsiw** [shedaniel/RoughlyEnoughItems#943] opened 2022-06-20 08:56 UTC
### What happened?

I loaded my Minecraft world with the mod, but blocks had no texture when I joined the world. Few seconds later, the game crash. I think REI is not compatible with 'Indium' and 'Continuity' mod after I checked the crash report.

I expected Minecraft to load normally with the mod.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
(I cannot use log out put because it has more than 65536 characters)
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/20/22, 2:03 PM
Description: Rendering entry

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.model.SpriteFinder.find(net.fabricmc.fabric.api.renderer.v1.mesh.QuadView, int)" because the return value of "me.pepperbell.continuity.client.util.RenderUtil.getSpriteFinder()" is null
	at me.pepperbell.continuity.client.model.EmissiveBakedModel$EmissiveItemQuadTransform.transform(EmissiveBakedModel.java:191)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:42)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.renderQuadWithTransform(ItemRenderContext.java:296)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:283)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:269)
	at net.minecraft.class_1087.emitItemQuads(class_1087.java:550)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitItemQuads(ForwardingBakedModel.java:56)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitItemQuads(EmissiveBakedModel.java:89)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:111)
	at net.minecraft.class_918.handler$daf000$hook_renderItem(class_918.java:2057)
	at net.minecraft.class_918.method_23179(class_918.java)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:257)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.render(ForwardingEntryRenderer.java:42)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:200)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:394)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:349)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:233)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:126)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:314)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:741)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:640)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:393)
	at net.minecraft.class_757.handler$zem000$renderScreenPost(class_757.java:6567)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.client.model.EmissiveBakedModel$EmissiveItemQuadTransform.transform(EmissiveBakedModel.java:191)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:42)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.renderQuadWithTransform(ItemRenderContext.java:296)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:283)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:269)
	at net.minecraft.class_1087.emitItemQuads(class_1087.java:550)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitItemQuads(ForwardingBakedModel.java:56)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitItemQuads(EmissiveBakedModel.java:89)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:111)
	at net.minecraft.class_918.handler$daf000$hook_renderItem(class_918.java:2057)
	at net.minecraft.class_918.method_23179(class_918.java)

-- Screen details --
Details:
	Screen name: net.minecraft.class_490
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:202)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:394)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:349)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:233)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:126)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:314)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:741)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:640)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:393)
	at net.minecraft.class_757.handler$zem000$renderScreenPost(class_757.java:6567)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: minecraft:coal_ore

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: coal_ore
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.class_490

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry
	Z level: 0
	Bounds: me.shedaniel.math.Rectangle@2120041a[height=18,width=18,x=678,y=80]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: minecraft:coal_ore

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: coal_ore
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.class_490

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (x86_64) version 12.4
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1537403128 bytes (1466 MiB) / 3758096384 bytes (3584 MiB) up to 3758096384 bytes (3584 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: unknown
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 6000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x1626
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 11264.00
	Virtual memory used (MB): 6889.73
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 1714.00
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx3572M -Xss1M
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.13
		advancednetherite: Advanced Netherite 1.6.0-1.19
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		alwaysawitherskull-fabric: Always a Wither Skull (Fabric) 1.6
		appleskin: AppleSkin 2.4.0+mc1.19
		archeology: CapsLock Archeology Mod 0.1.9
		architectury: Architectury 5.7.27
		armorchroma: Armor Chroma 1.2.2
		autoswitch: AutoSwitch 5.1.0
			autoswitch-api: AutoSwitch API 1.1.0
			org_aeonbits_owner_owner: owner 1.0.12
		balm-fabric: Balm 4.0.0+0
		bclib: BCLib 2.0.5
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterend: Better End 2.0.2
		betterf3: BetterF3 1.3.0
		bettermounthud: Better Mount HUD 1.1.4
		betterspawnercontrol-fabric: Better Spawner Control (Fabric) 1.7
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 14.0.2
		boostedbrightness: Boosted Brightness 2.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.7.56
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.7.56
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.7.56
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.7.56
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.7.56
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.7.56
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.7.56
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.7.56
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.7.56
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.7.56
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.7.56
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.7.56
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.7.56
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.7.56
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.7.56
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.7.56
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.7.56
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.7.56
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.7.56
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.7.56
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.7.56
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			org_threadly_threadly: threadly 7.0
		cardinal-components: Cardinal Components API 5.0.0-beta.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		cem: Custom Entity Models 0.7.1
		chat_heads: Chat Heads 0.6.0
		chatlagremover: ChatLagRemover 1.0
		chunky: Chunky 1.2.186
		clickthrough: ClickThrough 1.19-fabric0.53.3-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		clientsidenoteblocks: ClientSideNoteblocks 2.2
		climbladdersfast: ClimbLaddersFast 3.0-1.19
		cloth-config: Cloth Config v6 7.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		colormatic: Colormatic 3.1.2+mc.1.19
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+1
		creativecore: CreativeCore (Fabric) 2.7.0
		cull-less-leaves: Cull Less Leaves 1.0.2
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		cullleaves: Cull Leaves 2.3.4
		cullparticles: Cull Particles 2.0
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		debugify: Debugify 2.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		doubledoors-fabric: Double Doors (Fabric) 3.4
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.8.1
		ecs: Elytra/Chestplate Swapper 1.2.1-MC1.19
		emotecraft: Emotecraft 2.1.3-SNAPSHOT-build.29
			bendy-lib: Bendy api 2.0.4
		entity_texture_features: Entity Texture Features 3.0.0
		entityculling: EntityCulling-Fabric 1.5.1-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		extendedbonemeal-fabric: Extended Bone Meal (Fabric) 1.7
		fabric: Fabric API 0.56.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.13+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.0+4a3ec384a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.8+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.7
		fallingtree: FallingTree 3.6.0
		ferritecore: FerriteCore 4.2.1
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.8
		forgeconfigapiport: Forge Config API Port 4.0.0
		forgivingvoid: Forgiving Void 7.0.0
		freecam: Freecam 1.0.6
		grindenchantments: Grind Enchantments 1.6.4+1.19
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.5
		indium: Indium 1.0.4+mc1.19
		infinitetrading-fabric: Infinite Trading (Fabric) 2.2
		inventoryprofilesnext: Inventory Profiles Next 1.5.0
		itemphysiclite: ItemPhysic Lite (Fabric) 1.5.0
		jamlib: JamLib 0.0.6
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		languagereload: Language Reload 1.2.4
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.0
		logical_zoom: Logical Zoom 0.0.15
		memoryleakfix: memory Leak Fix 1.19-0.4.0
		merenc: Merge Enchantments 1.4
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		morecosmetics: MoreCosmetics 1.1.1
		morevillagers: More Villagers 4.0.1
		nofade: No Fade 1.18-2.0.1
		nostrip: No Strip 1.2.2-1.17+
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		rightclickharvest: Right Click Harvest 2.0.8
		roughlyenoughitems: Roughly Enough Items 9.0.491
		servercore: ServerCore 1.3.0-1.19
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-beta.3+1.19
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9-beta.1+1.19-rc2
			mm: Manningham Mills 2.3
		signtools: Sign Tools 1.0.0
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		spawnermod: Enhanced Mob Spawners 1.1.3
		starlight: Starlight 1.1.0+fabric.eb9df34
		taxfreelevels: Tax Free Levels 1.3
		trade_cycling: Trade Cycling 1.19-1.0.2
		uncraftingtable76: UncraftingTable 1.19-1.0.2
			mcpitanlib: MCPitanLib 1.4.3
		worldedit: WorldEdit 7.2.11-SNAPSHOT+6185-69b5d66
	Suspected Mods: Indium (indium), Minecraft (minecraft), Fabric Renderer API (v1) (fabric-renderer-api-v1), Fabric Loader (fabricloader), Continuity (continuity), Roughly Enough Items (roughlyenoughitems)
```

**Comment by ghost** [comment] 2022-07-18 22:40
Adding some context here - the cause is that `me.pepperbell.continuity.client.util.RenderUtil.getSpriteFinder()` is being called (somehow) by this mod before Continuity ever expects it to be, and at that point in time the variable it returns has not yet been provided with a value (this is done in the reload method inside of a `ReloadListener` in the class).

I have made a PR to fix it on Continuity's side, however, @PepperCode1 makes a good point - it may be better fixed on REI's side, given that apart from specifically this mod it appears that the current logic works perfectly fine.

**Comment by ryleu** [comment] 2022-07-19 19:37
A fix on both sides would be ideal.

**Comment by shedaniel** [comment] 2022-07-20 09:16
@PepperCode1 I am not sure if this is supposed to be a REI issue, it could very well be, but I don't think that's the case here.

From the logs, the user has opened InventoryScreen, so they are already in the world, so I don't think REI is necessarily rendering it too early per say.

I am not too familiar with the vanilla reload system, but it should be reloaded by the time the user has entered the world right?

**Comment by shedaniel** [comment] 2022-09-17 18:36
Please re-open the issue if this is an REI issue, as the comment above.

**Closed as completed by shedaniel** 2022-09-17 18:36 UTC
Labels: bug
