### ISSUE TITLE
[Bug] Crash when clicking the + button without having all required items

### ISSUE THREAD

**Issue by angelnc1989** [shedaniel/RoughlyEnoughItems#85] opened 2019-05-07 06:09 UTC
**Describe the bug**
Every time I click the + button without having all required items to craft the item, the game crashes.

**Steps to Reproduce**
- Look up any recipe without having the required items to craft it
- Click or shift-click the + button

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14
 - Mod Loader: Fabric

**Logs**
https://pastebin.com/JdixZzfh

**Comment by shedaniel** [comment] 2019-05-07 10:07
Can't reproduce yet, I tried on singleplayer but it didn't crash.
![image](https://user-images.githubusercontent.com/34910653/57291903-fb2df380-70f2-11e9-9ce5-1e4841372e82.png)
This is what should happen.

The crash log has something to do with rendering the red stuff.

**Comment by shedaniel** [comment] 2019-05-10 08:03
I am closing this issue! Please inform me if this keeps occurring.

**Closed as completed by shedaniel** 2019-05-10 08:03 UTC
Labels: bug, note: not reproducible
