### ISSUE TITLE
[Bug] about shift button doesn't work

### ISSUE THREAD

**Issue by lucioussing** [shedaniel/RoughlyEnoughItems#1698] opened 2024-08-06 14:41 UTC
### What happened?

64 wheat could craft into more Haystack. but,64 wheat could not craft more bread ,it's just allow 3 wheat==>1 bread.shift button is Not running,click shift and click ,couldn't let all wheat change to bread.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[22:31:50] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:31:50] [REI-AsyncSearchManager-20/TRACE] [REI] Search "" Used [Thread[#205,REI-AsyncSearchManager-20,10,main]]: 11.07 ms
[22:31:50] [REI-AsyncSearchManager-20/TRACE] [REI] Search "" Used and Applied [Thread[#205,REI-AsyncSearchManager-20,10,main]]: 11.17 ms
[22:31:50] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:31:50] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:31:50] [REI-AsyncSearchManager-20/TRACE] [REI] Search "" Used [Thread[#205,REI-AsyncSearchManager-20,10,main]]: 12.58 ms
[22:31:50] [REI-AsyncSearchManager-20/TRACE] [REI] Search "" Used and Applied [Thread[#205,REI-AsyncSearchManager-20,10,main]]: 12.67 ms
[22:31:50] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:31:50] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:31:50] [REI-AsyncSearchManager-20/TRACE] [REI] Search "" Used [Thread[#205,REI-AsyncSearchManager-20,10,main]]: 10.83 ms
[22:31:50] [REI-AsyncSearchManager-20/TRACE] [REI] Search "" Used and Applied [Thread[#205,REI-AsyncSearchManager-20,10,main]]: 10.91 ms
[22:33:13] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:13] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:13] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.17 ms
[22:33:13] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used and Applied [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.32 ms
[22:33:13] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:13] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:13] [REI-AsyncSearchManager-21/TRACE] [REI] Search "" Used [Thread[#282,REI-AsyncSearchManager-21,10,main]]: 9.694 ms
[22:33:13] [REI-AsyncSearchManager-21/TRACE] [REI] Search "" Used and Applied [Thread[#282,REI-AsyncSearchManager-21,10,main]]: 9.776 ms
[22:33:22] [Render thread/TRACE] [REI] Built Recipe View in 2.052 ms for 0 categories, 0 recipes for, 1 usages for and 0 live recipe generators.
[22:33:22] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:22] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:22] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 10.96 ms
[22:33:22] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used and Applied [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 11.05 ms
[22:33:29] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:29] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:29] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 11.35 ms
[22:33:29] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used and Applied [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 11.46 ms
[22:33:29] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:29] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:29] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 12.21 ms
[22:33:29] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used and Applied [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 12.30 ms
[22:33:30] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:30] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:30] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.06 ms
[22:33:30] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used and Applied [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.13 ms
[22:33:31] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:31] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:31] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.44 ms
[22:33:31] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used and Applied [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.52 ms
[22:33:31] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:31] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:31] [REI-AsyncSearchManager-21/TRACE] [REI] Search "" Used [Thread[#282,REI-AsyncSearchManager-21,10,main]]: 10.70 ms
[22:33:31] [REI-AsyncSearchManager-21/TRACE] [REI] Search "" Used and Applied [Thread[#282,REI-AsyncSearchManager-21,10,main]]: 10.79 ms
[22:33:32] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:32] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:32] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 10.62 ms
[22:33:32] [REI-AsyncSearchManager-18/TRACE] [REI] Search "" Used and Applied [Thread[#201,REI-AsyncSearchManager-18,10,main]]: 10.70 ms
[22:33:32] [Render thread/DEBUG] [REI] Starting Search: "" with 1549 stacks, shouldAsync: true on Render thread
[22:33:32] [Render thread/DEBUG] [REI] Async Search: 4 partitions for ""
[22:33:32] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.62 ms
[22:33:32] [REI-AsyncSearchManager-19/TRACE] [REI] Search "" Used and Applied [Thread[#202,REI-AsyncSearchManager-19,10,main]]: 10.70 ms
```

### Anything else?

nope

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2024-08-06 15:34
Duplicate of #1679

**Closed as not planned** 2024-08-06 15:34 UTC
Labels: bug, status: duplicate
