### ISSUE TITLE
search for items in the inventory does not work in Russian

### ISSUE THREAD

**Issue by Varkaus** [shedaniel/RoughlyEnoughItems#1417] opened 2023-05-27 17:51 UTC
### What happened?

After switching the game language from English to Russian, the search mode stopped working, but the rest of the functions work.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
nope
```

### Anything else?

nope

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Varkaus** [comment] 2023-05-27 17:52
I reinstalled the game, the problem is not solved.

**Comment by shedaniel** [comment] 2023-05-28 02:12
Duplicate of #1297

**Closed as not planned** 2023-05-28 02:12 UTC
Labels: bug, status: duplicate
