### ISSUE TITLE
[Bug] Pretty Pipes - Ghost Slots

### ISSUE THREAD

**Issue by Sunekaer** [shedaniel/RoughlyEnoughItems#1216] opened 2022-11-13 16:28 UTC
### What happened?

Mod: Pretty Pipes

    Attach a Pretty Pipes crafting terminal to a chest with items in it via a pipe and open the UI.
    Go to REI and click on any recipe that doesn't use all 9 crafting slots.
    Click the + button to send the recipe to the crafting terminal.
    The recipe doesn't get sent over. If you repeat steps 2 and 3 with a recipe that uses all 9 slots, it should work as intended.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[13Nov2022 17:27:03.401] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@2e607827, suppressing error
java.lang.NullPointerException: Cannot invoke "de.ellpeck.prettypipes.packets.PacketGhostSlot$Entry.getStacks()" because the return value of "java.util.Map.get(Object)" is null
	at de.ellpeck.prettypipes.terminal.CraftingTerminalBlockEntity.setGhostItems(CraftingTerminalBlockEntity.java:65) ~[PrettyPipes-1.12.8.jar%23208!/:1.12.8]
	at de.ellpeck.prettypipes.packets.PacketGhostSlot.lambda$onMessage$0(PacketGhostSlot.java:64) ~[PrettyPipes-1.12.8.jar%23208!/:1.12.8]
	at de.ellpeck.prettypipes.packets.PacketGhostSlot$2.run(PacketGhostSlot.java:82) ~[PrettyPipes-1.12.8.jar%23208!/:1.12.8]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at de.ellpeck.prettypipes.packets.PacketGhostSlot.onMessage(PacketGhostSlot.java:79) ~[PrettyPipes-1.12.8.jar%23208!/:1.12.8]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.1.84-universal.jar%23270!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1439) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23265!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13Nov2022 17:28:11.977] [MT Profile Update Thread 61/WARN] [net.creeperhost.minetogether.lib.chat.profile.ProfileManager/]: Unexpected error response from API: Unable to locate user.
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Renari** [comment] 2022-11-17 13:26
https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/26

Relevant issue.

**Comment by shedaniel** [comment] 2022-11-17 16:08
Duplicate of https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/26

**Closed as completed by shedaniel** 2022-11-17 16:08 UTC
Labels: bug, status: duplicate
