### ISSUE TITLE
[issue ] Can't run your mod

### ISSUE THREAD

**Issue by Scorpions95** [shedaniel/RoughlyEnoughItems#1015] opened 2022-07-22 18:35 UTC
### What happened?

REI doesnt run, i mean i can't activate it, download all needed mods from here
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items
https://i.gyazo.com/19b97766528f2880e9ec72abc0729480.png

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9169906/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9169908/rei.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9169910/rei-issues.log)
i created a new issue topic as @shedaniel said
also attached latest, rei-issues, rei files

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
latest
rei
rei-issues
```

### Anything else?

i gues know evertthink is okay.
uploaded 3 files from logs folder

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-07-22 19:19
Duplicate of #983, this has already been fixed, please update REI, Architectury and Cloth Config, **PLEASE FUCKING READ WHATEVER CHECKBOX YOU ARE TICKING, YOU TICKED "By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.", THIS IS THE SECOND TIME ALREADY FOR GOD SAKE**

**Closed as completed by shedaniel** 2022-07-22 19:19 UTC
Labels: bug, status: duplicate, status: invalid
