### ISSUE TITLE
Issue when saving an item. [Bugs]

### ISSUE THREAD

**Issue by ChrisLensFlare** [shedaniel/RoughlyEnoughItems#527] opened 2021-05-04 03:18 UTC
**Describe the bug**
When saving an item within REI, the game crashes.

**Steps to Reproduce**
- Open REI
- Press the keybind for saving an item.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric 0.11.3

**Logs**
https://gist.githubusercontent.com/natanfudge/0ee91717cee4b446120b922eaf68dfbc/raw/039181c7586a364d1814d7284aef1ef4b0ea55ec/crash.txt

**Additional context**
The crash was on a server.

**Comment by shedaniel** [comment] 2021-05-05 23:48
Duplicate of #496

**Closed as completed by shedaniel** 2021-05-05 23:48 UTC
Labels: bug, status: duplicate
