### ISSUE TITLE
[Feature] Favourites Categories

### ISSUE THREAD

**Issue by DNAScanner** [shedaniel/RoughlyEnoughItems#710] opened 2022-01-10 19:39 UTC
**Describe the solution you'd like**
I'd like to have a new option in the favorites list (left) which allows you to add categories (on the plus button, bottom left) with maybe a custom name to set. You could either choose from a complete line-fillup or just a single slot. This would make favorites sorting so much easier.

**Comment by shedaniel** [comment] 2022-01-10 19:40
Duplicate of #388

**Closed as completed** 2022-01-10 19:40 UTC
Labels: status: duplicate, enhancement
