### ISSUE TITLE
[Bug] Crash on downloading server resource pack

### ISSUE THREAD

**Issue by Leo40Git** [shedaniel/RoughlyEnoughItems#313] opened 2020-04-12 09:37 UTC
**Describe the bug**
The game crashed after downloading a server's resource pack.

**Steps to Reproduce**
- Join Hypixel server (`mc.hypixel.net`)
- Go to Smash Heroes lobby
- Accept downloading the resource pack
- Wait for the resource pack to finish downloading
- Crash!

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric Loader 0.8.2+build.194

**Logs**
https://gist.githubusercontent.com/Cloak-Bot/2b193f2b09b5643aa04b9449586289e4/raw/5636330e9359dd56fb2bebeaf2f463266f0f8b53/crash.txt

**Comment by ghost** [comment] 2020-04-19 14:22
I'm having the exact same issue. I've had to remove some features from my server so that my players can use REI.

**Comment by shedaniel** [comment] 2020-04-19 14:53
I have a basic idea why this is happening.

**Comment by shedaniel** [comment] 2020-04-19 15:05
Please try v3.6.11 or v4.1.13-unstable to see if the issue is fixed.

**Comment by shedaniel** [comment] 2020-05-25 03:27
Should be fixed since there are no updates from the issue author.

**Closed as completed by shedaniel** 2020-05-25 03:27 UTC
Labels: bug
