### ISSUE TITLE
[Feature] Grouped Items in Favorites

### ISSUE THREAD

**Issue by sayore** [shedaniel/RoughlyEnoughItems#1158] opened 2022-10-17 21:12 UTC
### What is your feature request?

It would be really nice if you could have groups of favorites, like fore xample common stuff of Create, so you dont need to research stuff again and again in a tree of crafting.

Ideally they could be collapsible/nameable too.

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment] 2022-11-28 16:26
Duplicate of #388

**Closed as completed** 2022-11-28 16:26 UTC
Labels: status: duplicate, enhancement
