### ISSUE TITLE
[Bug] Cached Entry Rendering bug

### ISSUE THREAD

**Issue by UnusedCactus** [shedaniel/RoughlyEnoughItems#1480] opened 2023-08-16 16:50 UTC
### What happened?

With Cached Entry Rendering on in the latest 1.20.1 version, items and blocks are not rendered correctly in the non-favorites sidebar. Items are slightly darker, while blocks are rendered inside-out. All entries except liquids are also displayed upside down and in nearly reversed order.
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/87100678/23747c1a-6050-4a98-b32d-6807eeff0cce)
The same page as above as displayed without cached entry rendering on.
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/87100678/db8b427e-8d3e-49a6-9559-6ab7c099302f)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for START.
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] Plugins (19):
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) OwoReiPlugin of OwoReiPlugin [owo]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MythicMetalsREIClientPlugin of MythicMetalsREIClientPlugin [mythicmetals]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MeadowReiClientPluginFabric of MeadowReiClientPluginFabric [meadow]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FarmersDelightModREI of FarmersDelightModREI [farmersdelight]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REIChippedPlugin of REIChippedPlugin [chipped]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) CandlelightReiClientPluginFabric of CandlelightReiClientPluginFabric [candlelight]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BeachpartyREIClientPluginFabric of BeachpartyREIClientPluginFabric [beachparty]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BakeryReiClientPluginFabric of BakeryReiClientPluginFabric [bakery]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryClientPlugin of AlloyForgeryClientPlugin [alloy_forgery]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiPlugin of AdAstraReiPlugin [ad_astra]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryCommonPlugin of AlloyForgeryCommonPlugin [alloy_forgery]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiCommonPlugin of AdAstraReiCommonPlugin [ad_astra]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for START.
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] Plugins (14):
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) OwoReiPlugin of OwoReiPlugin [owo]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MythicMetalsREIClientPlugin of MythicMetalsREIClientPlugin [mythicmetals]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MeadowReiClientPluginFabric of MeadowReiClientPluginFabric [meadow]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FarmersDelightModREI of FarmersDelightModREI [farmersdelight]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REIChippedPlugin of REIChippedPlugin [chipped]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) CandlelightReiClientPluginFabric of CandlelightReiClientPluginFabric [candlelight]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BeachpartyREIClientPluginFabric of BeachpartyREIClientPluginFabric [beachparty]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BakeryReiClientPluginFabric of BakeryReiClientPluginFabric [bakery]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryClientPlugin of AlloyForgeryClientPlugin [alloy_forgery]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiPlugin of AdAstraReiPlugin [ad_astra]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[12:06:00] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[12:06:07] [Render thread/INFO]: [STDOUT]: Finalizing fluid item registration
[12:06:07] [Render thread/INFO]: [STDOUT]: Finalizing energy item registration
[12:06:10] [Render thread/INFO]: Minimap updated server level id: 860388435 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[12:06:10] [Render thread/INFO]: Loaded 10 advancements
[12:06:10] [Render thread/INFO]: [WTHIT] Received config from the server: {"minecraft:override.invisible_entity":true,"minecraft:attribute.horse_jump_height":true,"minecraft:spawner_type":true,"wailax:progress.enabled_block":true,"minecraft:note_block.type":true,"minecraft:level.composter":true,"minecraft:override.infested":true,"minecraft:attribute.horse_speed":true,"wailax:item.enabled_entity":true,"wailax:progress.enabled_entity":true,"minecraft:item_entity":true,"minecraft:breaking_progress.enabled":true,"minecraft:redstone.lever":true,"minecraft:jukebox.record":true,"wailax:energy.enabled_entity":true,"minecraft:timer.breed":true,"wailax:fluid.enabled_block":true,"minecraft:redstone.comparator":true,"wailax:item.enabled_block":true,"minecraft:override.trapped_chest":true,"minecraft:attribute.health":true,"wailax:item.nbt":true,"minecraft:attribute.armor":true,"minecraft:pet.owner":true,"wailax:energy.enabled_block":true,"minecraft:attribute.absorption":true,"wailax:fluid.enabled_entity":true,"minecraft:redstone.level":true,"minecraft:timer.grow":true,"minecraft:level.honey":true,"minecraft:crop_progress":true,"minecraft:redstone.repeater":true,"minecraft:player_head.name":true,"minecraft:override.powder_snow":true}
[12:06:13] [Render thread/INFO]: Reloading entity icon resources...
[12:06:13] [Render thread/INFO]: Done!
[12:06:13] [Render thread/INFO]: [REI] Refreshing cached entry list texture...
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for START.
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] Plugins (5):
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryCommonPlugin of AlloyForgeryCommonPlugin [alloy_forgery]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiCommonPlugin of AdAstraReiCommonPlugin [ad_astra]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[12:06:15] [REI-ReloadPlugins/INFO]: [WTHIT] Show recipe action set for Roughly Enough Items
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for START in 2.584 ms, totaling 77.22 ms.
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 1.503 ms, totaling 14.55 s.
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for START in 495.0 ?s, totaling 3.116 ms.
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] ========================================
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for END.
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] Plugins (19):
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) OwoReiPlugin of OwoReiPlugin [owo]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MythicMetalsREIClientPlugin of MythicMetalsREIClientPlugin [mythicmetals]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MeadowReiClientPluginFabric of MeadowReiClientPluginFabric [meadow]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FarmersDelightModREI of FarmersDelightModREI [farmersdelight]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REIChippedPlugin of REIChippedPlugin [chipped]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) CandlelightReiClientPluginFabric of CandlelightReiClientPluginFabric [candlelight]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BeachpartyREIClientPluginFabric of BeachpartyREIClientPluginFabric [beachparty]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BakeryReiClientPluginFabric of BakeryReiClientPluginFabric [bakery]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryClientPlugin of AlloyForgeryClientPlugin [alloy_forgery]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiPlugin of AdAstraReiPlugin [ad_astra]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryCommonPlugin of AlloyForgeryCommonPlugin [alloy_forgery]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiCommonPlugin of AdAstraReiCommonPlugin [ad_astra]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] ========================================
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] Plugins (14):
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) OwoReiPlugin of OwoReiPlugin [owo]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MythicMetalsREIClientPlugin of MythicMetalsREIClientPlugin [mythicmetals]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) MeadowReiClientPluginFabric of MeadowReiClientPluginFabric [meadow]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FarmersDelightModREI of FarmersDelightModREI [farmersdelight]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REIChippedPlugin of REIChippedPlugin [chipped]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) CandlelightReiClientPluginFabric of CandlelightReiClientPluginFabric [candlelight]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BeachpartyREIClientPluginFabric of BeachpartyREIClientPluginFabric [beachparty]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) BakeryReiClientPluginFabric of BakeryReiClientPluginFabric [bakery]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryClientPlugin of AlloyForgeryClientPlugin [alloy_forgery]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiPlugin of AdAstraReiPlugin [ad_astra]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[12:06:15] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[12:06:15] [Render thread/INFO]: [REI] Refreshing cached entry list texture...
[12:06:18] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[12:06:18] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for END.
[12:06:18] [REI-ReloadPlugins/INFO]: [REI] Plugins (5):
[12:06:18] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:06:18] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:06:18] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:06:18] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AlloyForgeryCommonPlugin of AlloyForgeryCommonPlugin [alloy_forgery]
[12:06:18] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AdAstraReiCommonPlugin of AdAstraReiCommonPlugin [ad_astra]
[12:06:18] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[12:06:18] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for END in 818.1 ?s, totaling 80.83 ms.
[12:06:18] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 1.425 ms, totaling 3.070 s.
[12:06:18] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for END in 492.5 ?s, totaling 13.79 ms.
[12:06:40] [Render thread/INFO]: [REI] Preparing cached texture with size 7232x7232 for 113x113 entries
```

### Anything else?

_Mod list from latest.log_
- ad_astra 1.15.3
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- alloy_forgery 2.0.22+1.20
	- architectury 9.1.12
	- athena 3.0.1
	- badpackets 0.4.1
	- bakery 1.1.2
	- beachparty 1.1.2
	- beautify 1.0.0+1.20
	- betterarcheology 1.0.2
	- botarium 2.2.0
	   \-- team_reborn_energy 3.0.0
	- candlelight 1.2.4
	- chipped 3.0.1
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- doapi 1.2.6
	   \-- terraform-wood-api-v1 7.0.1
	- entityculling 1.6.2-mc1.20
	- explorify v1.3.0-mc1.20u1.20.1
	- fabric-api 0.87.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.2+6bdb2ed077
	   |-- fabric-renderer-indigo 1.4.2+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.8+kotlin.1.9.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.22
	- farmersdelight 1.20.1-1.4.1
	- ferritecore 6.0.0
	- forgero 0.10.9.4+1.20.1
	   |-- advanced_runtime_resource_pack 0.6.7
	   |-- forgero-common 0.10.9.4+1.20.1
	   |-- forgero-compat 0.10.9.4+1.20.1
	   |-- forgero-core 0.10.9.4+1.20.1
	   |-- forgero-extended 0.10.9.4+1.20.1
	   |-- forgero-fabric-compat 0.10.9.4+1.20.1
	   |-- forgero-fabric-core 0.10.9.4+1.20.1
	   |-- forgero-structures 0.10.9.4+1.20.1
	   \-- forgero-vanilla 0.10.9.4+1.20.1
	- handcrafted 3.0.1
	- java 17
	- lazydfu 0.1.3
	- lithium 0.11.2
	- meadow 1.2.0
	- memoryleakfix 1.1.1
	- mine_treasure_mr 1.2.9
	- minecraft 1.20.1
	- modmenu 7.2.1
	- mythicmetals 0.18.2+1.20
	   |-- additionalentityattributes 1.4.0+1.20.0
	   |-- cardinal-components-base 5.2.0
	   |-- cardinal-components-entity 5.2.0
	   |-- common-protection-api 1.0.0
	   \-- reach-entity-attributes 2.3.3-pre.2
	- notenoughcrashes 4.4.6+1.20.1
	- owo 0.11.1+1.20
	   \-- blue_endless_jankson 1.2.2
	- reeses-sodium-options 1.6.4+mc1.20.1-build.94
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.9
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- roughlyenoughitems 12.0.645
	   \-- error_notifier 1.0.9
	- smoothboot 1.19.4-1.7.0
	- sodium 0.5.1
	- terrablender 3.0.0.169
	   |-- com_electronwill_night-config_core 3.6.4
	   \-- com_electronwill_night-config_toml 3.6.4
	- wthit 8.3.1
	- xaerominimap 23.6.2
	- xaeroworldmap 1.33.0

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by pointydev** [comment] 2023-08-18 18:41
I've also had this issue and posted a comment on #1271 where it was also being experienced by others.

**Comment by shedaniel** [comment] 2023-09-01 08:50
Duplicate of #1271
This is now fixed in the latest version.

**Closed as not planned by shedaniel** 2023-09-01 08:50 UTC
Labels: bug, status: duplicate
