### ISSUE TITLE
[Bug] Crash with journymap in latest versions 1.19.2

### ISSUE THREAD

**Issue by papillo12** [shedaniel/RoughlyEnoughItems#1136] opened 2022-09-26 02:26 UTC
### What happened?

I recently updated several mods and had to roll back to a previous version because it says journymap doesn't work. 

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
I can't upload the files in this part, could you change it?
```

### Anything else?

![imagen_2022-09-25_202337618](https://user-images.githubusercontent.com/80440525/192181562-c5de0dc3-80a5-4ab0-b84e-e39c792a4e8b.png)

logs:
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9642477/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9642478/rei.log)

crashreport:
[crash-2022-09-25_20.20.46-fml.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9642487/crash-2022-09-25_20.20.46-fml.txt)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by papillo12** [comment] 2022-09-26 02:30
I rolled back your mods, the others had no incompatibility.

**Comment by mysticdrew** [comment] 2022-09-27 21:38
This is happening due to a race condition with a recently added InputConstants.isKeyDown mixin in REI. I have applied a fix on my end, but it may be a while before the next JM release is published.

**Comment by shedaniel** [comment] 2022-09-28 09:24
Duplicate of #1134

**Closed as completed by shedaniel** 2022-09-28 09:24 UTC
Labels: bug
