### ISSUE TITLE
[Bug] Crafting recipes NOT showing up

### ISSUE THREAD

**Issue by Quizer9O8** [shedaniel/RoughlyEnoughItems#723] opened 2022-01-19 09:57 UTC
**Describe the bug**
Whenever I press R for a recipe I only get to see the Appearance select screen when using the mod for the first time and then no recipes other than the the Overworld Generation and Block Loot Drops from Roughly Not Enough Resources

**Steps to Reproduce**
- Open inventory
- Search an item with a recipe that should normally show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/19509275/150104600-d9e81cb9-e8c4-42bd-ab1d-b6323c2656c0.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric

**Logs**
https://mclo.gs/ITvdJ4X

**Additional context**
N/A

**Comment by shedaniel** [comment] 2022-01-29 07:31
Can you provide the client logs? Additionally, do you see the recipes in the vanilla recipe book?

**Comment by Omegarte** [comment] 2022-01-29 21:32
I basically am having the same issue.  REI loads fine but using r or u keys gives me no recipes other than if something is burnable or strippable (axes) or compostable.

**Comment by cannon9009** [comment] 2022-01-29 23:23
Same issue over here. Thought it was KubeJS but it was an unrelated issue (already fixed that, no worries there). Happens with both vanilla and modded items. Recipes do not appear in the vanilla book (the green book button), there isn't even any tabs... except the "All" tab. Posting log file.
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/7964974/latest.log)

**Comment by cannon9009** [comment] 2022-01-30 21:33
Here's a shorter log file where I tested it in a single world
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/7966963/latest.log)

**Comment by cannon9009** [comment] 2022-02-02 18:56
[One more log from another mod profile.](https://github.com/shedaniel/RoughlyEnoughItems/files/7989322/latest.log) @shedaniel

**Comment by mpeciakk** [comment] 2022-02-03 01:49
I had the same problem, I could craft all the items, but the recipes were not shown in the recipe book and rei. It seems that uninstalling universal graves fixed it

**Comment by cannon9009** [comment] 2022-02-03 02:03
> I had the same problem, I could craft all the items, but the recipes were not shown in the recipe book and rei. It seems that uninstalling universal graves fixed it

Oh, that's strange, for me it's Quarry Reborn causing a problem. Then again, I'm actually going through my modlist and seeing what mods cause what problems (multiple problems happening at once over here, just fixed one so far). Universal Graves isn't causing any troubles for me. Did you also have Quarry Reborn downloaded and possibly uninstalled it during your checks?

EDIT: Looks like I've been wrong. Universal Graves is the exact reason. Looks like some mods have a compatibility issue with it when REI is being used (which is probably what the issue with Quarry Reborn was about). Either uninstall mods that clash with U.G, or uninstall U.G.

**Comment by shedaniel** [comment] 2022-05-19 18:28
Caused by Universal Graves

**Closed as completed** 2022-05-19 18:28 UTC
Labels: bug, note: pending question
