### ISSUE TITLE
[Bug] Expanded tags view intersects with composite recipe screen type

### ISSUE THREAD

**Issue by Warhand** [shedaniel/RoughlyEnoughItems#1372] opened 2023-02-24 00:19 UTC
### What happened?

Expanded tags view is covered by aspects of the composite recipe screen type that don't vanish when the view is opened. They should disappear until the expanded view is closed, like other elements of the UI.

See attached image for an example

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
N/a
```

### Anything else?

![2023-02-23_18 21 09](https://user-images.githubusercontent.com/29134223/221054574-33286e36-8742-481b-bdb7-10c96779aac5.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-03-10 18:10
Duplicate of #1242

**Closed as not planned by shedaniel** 2023-03-10 18:11 UTC
Labels: bug, status: duplicate, priority: medium
