### ISSUE TITLE
[Bug] Support Block Tags

### ISSUE THREAD

**Issue by 800020h** [shedaniel/RoughlyEnoughItems#1325] opened 2023-01-15 10:09 UTC
### What happened?

when you search for tags, block tags don't show up

block tags have "recipes" so shouldn't they be searchable

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
n/a
```

### Anything else?

![image](https://user-images.githubusercontent.com/100995970/212534819-a3907516-8653-400e-91b6-81cfda47e468.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-05-29 12:02
Sorry, didn't see this, but closing as duplicate to #1391. Added in latest update.

**Comment by rozbrajaczpoziomow** [comment] 2023-05-29 12:11
Duplicate of a later issue lmfao.

**Comment by shedaniel** [comment] 2023-05-29 12:12
yeah that's why I apologised. too late now.

**Closed as not planned** 2023-05-29 12:12 UTC
Labels: bug, status: duplicate, enhancement
