### ISSUE TITLE
[Fabric Crash] REI crashing randomly when searching for any item in the search bar after a while in a world

### ISSUE THREAD

**Issue by Desempregago** [shedaniel/RoughlyEnoughItems#639] opened 2021-10-13 17:03 UTC
**Describe the bug:**
*the title describes what's happening*

**Steps to Reproduce:**
- Log in a world
- Search for something after a while in the world

**Environment:**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric 0.11.7 (with API 0.40.8)
- Roughly Enough Items 6.0.285-alpha (with Architectury 2.5.30)

**Logs**
[Crash Report](https://pastebin.com/EYtZZSKY)

**Additional Context**
I don't know if **IT IS** REI that is crashing, but I assume it might be owo (it makes a few changes in tooltips for Victus to work) or just REI misbehaving

**Comment by lospejos** [comment] 2021-10-16 02:00
I also faced this error.
I've read somewhere (don't remember exactly where) that this crash may be caused by Architecture mod, which is used in REI (AFAIK). Please note, this is just an assumption, I don't know exactly this is true.

BTW My crashlog contains this message:

```
Description: Getting tooltips
java.lang.IllegalArgumentException: Cannot set property class_2758{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}
```

**Comment by shedaniel** [comment] 2021-10-16 02:46
@lospejos Your specific crash is from Kibe.

**Comment by lospejos** [comment] 2021-10-16 11:20
@shedaniel 
Thanks for information!
Updating Kibe to a most recent at this moment version (kibe-1.9.3-BETA+1.17) didn't helped me, so I just removed it completely, and it helped.

**Comment by shedaniel** [comment] 2022-01-12 12:37
This should be fixed

**Closed as completed by shedaniel** 2022-01-12 12:37 UTC
Labels: bug
