### ISSUE TITLE
Exclusion Zones does not work with scrolled entry list

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#29] opened 2019-02-03 14:02 UTC
2.2.0.16/1.13.2 Rift fork
When mirroring REI, it expands enough to cover the potion effects and, if enabled, recipe book.

Among other things, it creates Z-fighting of the item tooltips and in some places of the recipe book, recipe book recipes are preferred over REI.

**Comment by shedaniel** [comment] 2019-02-03 14:04
I won't be able to fix item tooltips but I will fix the recipe books / potion effects.

**Comment by Madis0** [comment] 2019-02-16 14:26
Still happens on furnaces in 2.3.0.17.
Also, when enabling the recipe book but not showing it (on chests for example), REI becomes narrower than needed.

**Comment by shedaniel** [comment] 2019-02-16 16:57
Unfortunately I won't be fixing it again for 1.13.x as Forge is here, I will see if it reproduce in Fabric

**Comment by shedaniel** [comment] 2019-02-17 08:46
![image](https://user-images.githubusercontent.com/34910653/52910518-8efdd980-32d3-11e9-83a2-3c14362581a1.png)
Can't reproduce in v2.3.0.18

**Comment by Madis0** [comment] 2019-04-30 16:31
REI 2.8.0 b 100, Fabric Loader 0.4.6 b 141, Minecraft 1.14
Can reproduce on all gamemodes with recipe book disabled. (Recipe book itself does not have the issue)

![Effect bug](https://user-images.githubusercontent.com/8611110/56977563-17271780-6b7e-11e9-86a5-2a658647a317.png)

**Comment by shedaniel** [comment] 2019-04-30 16:40
Reproduced

**Comment by Madis0** [comment] 2019-08-18 17:04
3.0 pre1 covers both effects and recipe book again.

**Comment by shedaniel** [comment] 2019-08-18 17:09
I will look into this tmr

**Comment by Madis0** [comment] 2019-08-18 17:34
~To clarify: this does _not_ happen when REI and Fabric API are the only mods, so I guess there might be some conflict with some another mod. Will report once I find out, which.~

**Comment by shedaniel** [comment] 2019-08-19 13:23
I can't reproduce. Logs?

**Comment by Madis0** [comment] 2019-08-19 14:15
Found the cause - this happens when setting _entry list action_ to _scrolled_ and scrolling a bit down.  REI only makes room for the first visible set of items.

[Gallery](https://imgur.com/a/mwvkuwc)

**Comment by shedaniel** [comment] 2019-08-19 14:15
Reproduced

**Comment by shedaniel** [comment] 2019-08-20 07:22
If the list scrolls by slots, this would be easier to fix, I am thinking a way to fix this without making it weird to scroll

**Closed as completed** 2019-11-26 13:00 UTC
Labels: bug
