### ISSUE TITLE
[Bug] Search bar does not work.

### ISSUE THREAD

**Issue by vainlaind4in** [shedaniel/RoughlyEnoughItems#1379] opened 2023-03-11 14:45 UTC
### What happened?

Forge 1.19.2
Roughly Enough Items Version 9.1.591

I'm playing on the latest version of REI and on the All The Mods 8 modpack with extra mods I myself added in. I replaced the Just Enough Items from the modpack to Roughly Enough Items along with some of it's addons, since this alternative was better in many ways. However, I do have a major problem that's arising.

The searching feature for Roughly Enough Items does not work. Every time I try to search something, it does not work, and nothing that relates to my search pops up. It just stays the way it is. Searching by mods does work though.

I have searched for other issues, and they seem to stem from a mod with invalid tooltips of some sort and they somehow have already been fixed. However, this occurs on the later versions of the mod, and I do not know what is really causing it.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Since my latest.log is over 280k lines long, I am unable to paste all of it inside of a gist.

Here's the rei.log:
https://gist.github.com/vainlaind4in/e377bc663c91c4dc99c142e4b39394ce
Here's the rei-issues.log:
https://gist.github.com/vainlaind4in/d2c11356f692b3387ed9a688ce9aa188
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-03-11 14:59
Duplicate of #1297

**Closed as not planned by shedaniel** 2023-03-11 14:59 UTC
Labels: bug, status: duplicate
