### ISSUE TITLE
[Bug] Error from 'errornotifier' from rei causing logspam

### ISSUE THREAD

**Issue by slushieuwu** [shedaniel/RoughlyEnoughItems#1335] opened 2023-01-20 21:00 UTC
### What happened?

The logspam is so fast, it reaches over 100000 lines in only about 5 seconds, and it makes game stop responding before the loading screen even appears

also im using quilt, but thats not an option below so i picked fabric

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
log is far too big to send here so: https://gist.github.com/DmanMC/597c6cbd1ff9cfc615068cee7ecaeb09
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [x] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-01-21 05:09
Duplicate of #1248
This is an issue from Quilt Loader, REI is a Fabric mod and Quilt Loader should attempt to support such
the fix in Quilt Loader is currently in beta, maybe just hurry them up? :p

**Closed as not planned by shedaniel** 2023-01-21 05:09 UTC
Labels: bug, status: duplicate, status: invalid, env: quilt
