### ISSUE TITLE
[Bug]Crash on startup

### ISSUE THREAD

**Issue by SirKrunk** [shedaniel/RoughlyEnoughItems#749] opened 2022-01-30 04:02 UTC
**Describe the bug**
Crash on startup using latest fabric 1.18.1 versions, forced to use version [Fabric 1.18.x] v7.2.405

**Steps to Reproduce**
- Startup
- Crashes
- changed version to [Fabric 1.18.x] v7.2.405
- it works

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
 - Mod Loader: [e.g. forge, fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[crash-2022-01-30_09.54.52-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/7965271/crash-2022-01-30_09.54.52-client.txt)

**Additional context**

**Comment by shedaniel** [comment] 2022-01-30 06:03
Duplicate of #746, please **search** before reporting an issue.

**Closed as completed** 2022-01-30 06:04 UTC
Labels: bug, status: duplicate, status: invalid

**Comment by SirKrunk** [comment] 2022-01-30 08:08
ok
