### ISSUE TITLE
[Bug] Game crashes on recipe shift click

### ISSUE THREAD

**Issue by rlnt** [shedaniel/RoughlyEnoughItems#104] opened 2019-06-06 18:11 UTC
**Describe the bug**
The game crashes when I try to shift click a recipe to the crafting table.

**Steps to Reproduce**
- Place and open a crafting table
- Search for an item in REI and open its recipe
- Shift click the plus sign in the recipe overlay
- The game crashes

**Environment (please complete the following information with the version):**
 - Minecraft 1.14.2
 - Mod Loader Fabric
 - MultiMC Launcher

**Logs**
https://pastebin.com/Ki4H7Nvr

**Comment by shedaniel** [comment] 2019-06-07 02:49
Can you try to reproduce the issue with the latest REI version? Thanks

**Comment by shedaniel** [comment] 2019-06-08 11:57
Alright let's just say this is a duplicate of #24 when it is technically not.

**Closed as completed by shedaniel** 2019-06-08 11:57 UTC
Labels: bug
