### ISSUE TITLE
Search bar not working [1.19]

### ISSUE THREAD

**Issue by bluejuju** [shedaniel/RoughlyEnoughItems#1104] opened 2022-08-27 13:57 UTC
### What happened?

So I'm playing on a modpack on curseforge called [The Unofficial OriginSMP](https://www.curseforge.com/minecraft/modpacks/the-unofficial-origin-smp)
and I can't search items with REI. The Modpack has a server and it works for everyone on that server and they play with the same modpack as I am but it won't work for me somehow. I reinstalled the modpack, reinstalled the .jar REI file and replaced it with the same update and even put in the newer one Fabric 1.19-1.19.2 v9.1.530.
I saw that problems could be because of the mod "Extra Generators" but that doesn't explain, why it works for everyone but me.
This problem got closed due lack of logs. I did say if needed I can provide them so guess I'll do it this time. It says "Comment too long", that's why I said, I can provide them if needed!

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/bluejuju/34714779fe0e9f6149cd00dafe065775

This problem got closed due lack of logs I'll do it this time. It said "Comment too long". Link above has the logs from latest, rei and rei-issues.

IF ANYTHING IS MISSING, PLEASE LET ME KNOW!
```

### Anything else?

https://www.curseforge.com/minecraft/modpacks/the-unofficial-origin-smp

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by bluejuju** [comment] 2022-08-27 15:06
EDIT: I made a small error!!! **The Server is not running Forge, it's running on Fabric!**

**Comment by shedaniel** [comment] 2022-08-27 15:46
@lucaargolo This issue is still happening, please consider adding the check

**Comment by shedaniel** [comment] 2022-09-17 18:41
Duplicate of #1034

**Closed as completed by shedaniel** 2022-09-17 18:41 UTC
Labels: bug, status: duplicate
