### ISSUE TITLE
search bar isnt working

### ISSUE THREAD

**Issue by kabringus** [shedaniel/RoughlyEnoughItems#994] opened 2022-07-14 06:05 UTC
### What happened?

i can type into the search box but nohting happens, this is within a modpack so is it something to do with that? is there any work around? on 1.19 btw

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
idk how to get logs very sorry, if someone gives me instructions i can
```

### Anything else?

its really annoying idk

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-07-14 14:09
Duplicate of #984, also no logs, you ticked the box that says you have the logs. Please have some responsibility.

**Closed as completed by shedaniel** 2022-07-14 14:09 UTC
Labels: bug, status: invalid

**Comment by kabringus** [comment] 2022-07-15 00:26
no, its not a dupe im in 1.19 that other person is in 1.82, i didnt know i could untick that box and if you look i ask someone to give me intructions to give logs, kinda disrespectful.
