### ISSUE TITLE
[Bug] Weird Behavior

### ISSUE THREAD

**Issue by HacoKavanah** [shedaniel/RoughlyEnoughItems#826] opened 2022-04-05 21:29 UTC
### What happened?

I was looking through the logs and saw this getting spammed around. Is this normal? It mentioned mostly rei so that why decided to com here.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: java.lang.IllegalStateException: Rendersystem called from wrong thread
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:181)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:170)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_4482(class_1041.java:222)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokePI(Native Method)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3409)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at net.minecraft.class_3675.method_15987(class_3675.java:465)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at potionstudios.byg.common.item.BYGSaplingItem.method_7851(BYGSaplingItem.java:44)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7950(class_1799.java:685)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:209)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:349)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.getTooltip(ForwardingEntryRenderer.java:48)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.api.client.entry.renderer.EntryRendererRegistry$1.getTooltip(EntryRendererRegistry.java:54)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:211)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:88)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:73)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:43)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.lambda$prepareFilter$0(Argument.java:266)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[00:01:22] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by shedaniel** [comment] 2022-04-08 17:44
Duplicate of #517

**Closed as completed by shedaniel** 2022-04-08 17:44 UTC
Labels: bug, status: duplicate
