### ISSUE TITLE
Crash (rei.api / cpas.runtime)

### ISSUE THREAD

**Issue by K0-RR** [shedaniel/RoughlyEnoughItems#592] opened 2021-08-01 11:27 UTC
**Steps to Reproduce**
I don't know, it happened when I was browsing recipes.

**Environment (please complete the following information with the version):**
Minecraft: 1.17.1
Mod Loader: Fabric

**Logs**
https://paste.ee/p/LWMUi

I see `at me.shedaniel.rei.api.client.registry.screen.ExclusionZones.getExclusionZones(ExclusionZones.java:41)`
but also `at badasintended.cpas.runtime.rei.CpasReiPlugin.lambda$registerExclusionZones$1(CpasReiPlugin.java:27)` so not sure which mod fault is it.

**Comment by SylisMC** [comment] 2021-08-25 23:14
i think i got the same crash here. 
[crash-2021-08-25_19.12.21-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/7050461/crash-2021-08-25_19.12.21-client.txt)

**Comment by shedaniel** [comment] 2022-01-15 19:28
Duplicate of #611

**Closed as completed by shedaniel** 2022-01-15 19:28 UTC
Labels: bug, status: duplicate
