### ISSUE TITLE
[Bug] Initialization Warning

### ISSUE THREAD

**Issue by uhhams** [shedaniel/RoughlyEnoughItems#1074] opened 2022-08-13 06:41 UTC
### What happened?

whenever I open the game, it give me a popup saying "The entrypoint used by NBT Crafting, "rei_plugins_v0" is deprecated and will be removed in a future version of Roughly Enough Items. Please use "rei_server"
"rei_client" or "rei_common" instead." It mightve also crashed my game when I tried opening singleplayer but im not sure.

Ive looked through the config and I dont see anywhere to input these. 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// You're mean.

Time: 8/12/22, 11:33 PM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'void net.minecraft.class_528.method_44677(java.lang.String)'
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at com.illusivesoulworks.cherishedworlds.client.favorites.FavoriteWorlds.init(FavoriteWorlds.java:43)
	at com.illusivesoulworks.cherishedworlds.client.ScreenEvents.onInit(ScreenEvents.java:62)
	at net.minecraft.client.gui.screen.world.SelectWorldScreen.handler$bnj001$cherishedworlds$init(SelectWorldScreen:1034)
	at net.minecraft.client.gui.screen.world.SelectWorldScreen.init(SelectWorldScreen:104)
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen:391)
	at net.minecraft.client.gui.screen.Screen.init(Screen:382)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1001)
	at net.minecraft.client.gui.screen.TitleScreen.method_19861(TitleScreen:158)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:120)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen:324)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:491)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:222)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1174)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.illusivesoulworks.cherishedworlds.client.favorites.FavoriteWorlds.init(FavoriteWorlds.java:43)
	at com.illusivesoulworks.cherishedworlds.client.ScreenEvents.onInit(ScreenEvents.java:62)
	at net.minecraft.class_526.handler$bnj001$cherishedworlds$init(class_526.java:1034)
	at net.minecraft.class_526.method_25426(class_526.java:104)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_442.method_19861(class_442.java:158)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:324)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, continuity/glass_pane_culling_fix, continuity/default, Fabric Mods, Xali's+Enchanced+Biome+River++Pond+v1.2.2, xali's+Enhanced+Jungle+Wood+v1.2.zip, xali's+Enchanted+Books+v0.9 (1).zip, KubeJS Resource Pack [assets]
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Anything else?

<img width="1022" alt="Screen Shot 2022-08-12 at 11 40 36 PM" src="https://user-images.githubusercontent.com/96365922/184472159-9dbb9874-c3cb-43d6-bab4-15f1da9b44a1.png">

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2022-08-14 04:55
Your crash is caused by cherishedworlds. The warning caused by NBT Crafting needs to be fixed by NBT Crafting.

**Closed as not planned** 2022-08-14 04:56 UTC
Labels: bug, status: invalid, other mods
